### ISSUE TITLE
Can not build libgpuarray

### ISSUE THREAD

**Issue by rizar** [Theano/libgpuarray#116]
Here is the output of `make`:

```
[  2%] Generating ../../src/gpuarray_types.c, ../../src/gpuarray/types.h
[  5%] Building C object src/CMakeFiles/gpuarray.dir/cache/lru.o
[  8%] Building C object src/CMakeFiles/gpuarray.dir/cache/twoq.o
[ 11%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_types.o
[ 14%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_error.o
[ 17%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_util.o
[ 20%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer.o
[ 23%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array.o
[ 26%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array_blas.o
[ 29%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_kernel.o
[ 32%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_extension.o
[ 35%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_strl.o
[ 38%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.o
/home/rizar/dist/libgpuarray/src/gpuarray_buffer_cuda.c: In function ‘call_compiler’:
/home/rizar/dist/libgpuarray/src/gpuarray_buffer_cuda.c:977:15: error: expected expression before ‘/’ token
/home/rizar/dist/libgpuarray/src/gpuarray_buffer_cuda.c:977:15: error: too few arguments to function ‘execl’
make[2]: *** [src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.o] Error 1
make[1]: *** [src/CMakeFiles/gpuarray.dir/all] Error 2
make: *** [all] Error 2
```

In addition, I tried to grep `NVCC_BIN`:

```
../build/src/CMakeFiles/gpuarray.dir/flags.make:C_FLAGS =  -Wall -O3 -DNDEBUG -fPIC -I/home/rizar/dist/libgpuarray/src -I/usr/local/cuda/include    -DNVCC_BIN="/usr/local/cuda/bin/nvcc"
../build/src/CMakeFiles/gpuarray-static.dir/flags.make:C_FLAGS =  -Wall -O3 -DNDEBUG -I/home/rizar/dist/libgpuarray/src -I/usr/local/cuda/include    -DNVCC_BIN="/usr/local/cuda/bin/nvcc"
../src/gpuarray_buffer_cuda.c:#define NVCC_ARGS NVCC_BIN, "-g", "-G", "-arch", arch_arg, "-x", "cu", \
../src/gpuarray_buffer_cuda.c:#define NVCC_ARGS NVCC_BIN, "-arch", arch_arg, "-x", "cu", \
../src/gpuarray_buffer_cuda.c:    sys_err = _spawnl(_P_WAIT, NVCC_BIN, NVCC_ARGS, NULL);
../src/gpuarray_buffer_cuda.c:        execl(NVCC_BIN, NVCC_ARGS, NULL);
../src/CMakeLists.txt:    add_definitions(-DNVCC_BIN="${CUDA_NVCC_EXECUTABLE}")
```

**Comment by nouiz** [comment]
This is strange. Thanks for the report. It would be better for you to
install nvtrc, this will work around this bug and will speed up compilation.

http://docs.nvidia.com/cuda/nvrtc/index.html#axzz3sby56kIJ

Which version of CUDA do you have? This is include in cuda 7.0 from memory.

**Comment by rizar** [comment]
On that machine I am apparently using CUDA 6.5 (see the output below). This is not a machine from the lab.

```
bin/nvcc --version 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_21:41:27_CDT_2014
Cuda compilation tools, release 6.5, V6.5.1
```

**Comment by nouiz** [comment]
I think this is fixed. If not, tell us and we can reopen it.

**Comment by abergeron** [comment]
Yes, it was resolved.

For other people, I'll note here that it was because there was a space in the path for NVCC and the cmake version that was in use mismanaged the required shell quoting.

Upgrading cmake or not using a path with spaces would fix this.

**Comment by NetBUG** [comment]
Got same issue with CUDA 7.5
`~/.pip/libgpuarray/Build# make
[  2%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.c.o
/root/.pip/libgpuarray/src/gpuarray_buffer_cuda.c: In function ‘call_compiler’:
<command-line>:0:10: error: expected expression before ‘/’ token
/root/.pip/libgpuarray/src/gpuarray_buffer_cuda.c:991:15: note: in expansion of macro ‘NVCC_BIN’
         execl(NVCC_BIN, NVCC_ARGS, NULL);
               ^
<command-line>:0:10: error: too few arguments to function ‘execl’
/root/.pip/libgpuarray/src/gpuarray_buffer_cuda.c:991:15: note: in expansion of macro ‘NVCC_BIN’
         execl(NVCC_BIN, NVCC_ARGS, NULL);
               ^
/root/.pip/libgpuarray/src/gpuarray_buffer_cuda.c: In function ‘cuda_error’:
/root/.pip/libgpuarray/src/gpuarray_buffer_cuda.c:1713:5: warning: implicit declaration of function ‘cuGetErrorString’ [-Wimplicit-function-declaration]
     cuGetErrorString(err, &errstr);
     ^
make[2]: *** [src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.c.o] Error 1
make[1]: *** [src/CMakeFiles/gpuarray.dir/all] Error 2
make: *** [all] Error 2
root@sujbiswa-70-90:~/.pip/libgpuarray/Build# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17`

**Comment by abergeron** [comment]
If you change the cuda version, you should remove the cmake dir and
re-configure from scratch.

If that is what you did, then your install is wierd since it should use
nvrtc instead of NVCC for cuda 7.5.

2016-07-01 16:52 GMT-04:00 Oleg <notifications@github.com>:

**Comment by dongfangyixi** [comment]
Came across with this problem again, I'm using "Cuda compilation tools, release 6.5, V6.5.12",  and I'm pretty sure there is no space in nvcc path, "/usr/local/cuda/bin/nvcc". Can any one help me with this?
