### ISSUE TITLE
where did the "Build" directory go?

### ISSUE THREAD

**Issue by nitbix** [Theano/libgpuarray#119]
In the installation instructions (http://deeplearning.net/software/libgpuarray/installation.html) you say to run make from within Build. That appears to have gone, and the only Makefile in here is in doc/

What is going on?

**Comment by abergeron** [comment]
If you read the instruction completely it also says to create a Build directory and to run cmake in it.

The instructions give a easy step-by-step but it doesn't work if you just skip to the end.

**Comment by nitbix** [comment]
Oh I somehow missed the "mkdir Build" bit. Thanks.
