### ISSUE TITLE
'import theano' doesn't work if I set device=gpu and contexts=dev0->cuda0;dev1->cuda1 in the same time

### ISSUE THREAD

**Issue by avostryakov** [Theano/libgpuarray#123]
If in .theanorc I set:

device = gpu
contexts=dev0->cuda0;dev1->cuda1
....

I will get the following error during 'import theano':

ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/gpuarray/__init__.py", line 76, in <module>
    if (config.device.startswith('cuda') or
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/gpuarray/__init__.py", line 52, in init_dev
    ctx = pygpu.init(dev)
  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:8909)
  File "pygpu/gpuarray.pyx", line 590, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8632)
  File "pygpu/gpuarray.pyx", line 1019, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12725)
GpuArrayException: cannot set while device is active in this process: 0

BUT If I remove "device = gpu" the import will work correctly.

**Comment by abergeron** [comment]
Yes, this is intentional.

Mixing the cuda and gpuarray backend is not supported.

**Comment by nouiz** [comment]
@abergeron, can you give a better error message in that case.

**Comment by angelsrates** [comment]
Hello!
I also removed device=gpu, but I am still getting the same error as @avostryakov 
Could please somebody help me?
I installed Theano 0.8.2 through Anaconda and I would like to use the gpu: Titan X Pascal with CUDA 7.5.

Thank you very much in advance!

**Comment by abergeron** [comment]
The TITAN X Pascal will not work with cuda 7.5.  Use cuda 8.0.

**Comment by angelsrates** [comment]
Oh okay! Thank you very much! I am currently on Ubuntu 14.4
Do you think that it will be any problem with CUDA 8.0?

Thanks!!!

**Comment by abergeron** [comment]
There is an official and supported download for ubuntu 14.04, so I don't see any special problems.

If you need further assistance, I would enjoin you to turn to the theano-users mailing list or stackoverflow, because the tickets are for bugs and new features.
