### ISSUE TITLE
Simple calls for 1d array construction

### ISSUE THREAD

**Issue by adler-j** [Theano/libgpuarray#125]
Numpy allows both type of calls:

```python
>>> numpy.zeros(3)
array([0, 0, 0])
>>> numpy.zeros([3])
array([0, 0, 0])
```

it would be nice libgpuarray did this aswell, currently the "non-list" case throws an error: "object of type 'int' has no len()".

**Comment by abergeron** [comment]
Yes, this is something we should fix.  Especially in pygpu, we try to match to numpy API (for the few things that are there).
