### ISSUE TITLE
Clarification of design goals

### ISSUE THREAD

**Issue by adler-j** [Theano/libgpuarray#126]
In an open source package for inverse problems ([odl](https://github.com/odlgroup/odl)), we're looking for an alternative CUDA backend with N-D support. libgpuarray looks interesting, but I have some questions that need clarification:

* libgpuarray is obviously tightly coupled with Theano, but is it intended to be used by other packages?

* Do you intend to accept external pull requests? Bug fixes or actual features?

* The documentation says: "we need a NumPy ndarray on the GPU". But in the default "GpuArray" you lack even the basics, such as addition, instead referencing users to compiling their own `ElemwiseKernel` because such methods would be un-optimized. Is the intent that libgpuarray should be a drop in for numpy, or is it intended to only support an optimized subset of it?

* Compilation times are currently great, but the payoff is that barely any functions are pre-compiled. Do you intend to ship libgpuarray with the standard ufuncs (`add`, `exp`, etc) compiled, or should we do that in our own library?

**Comment by abergeron** [comment]
- Yes, the original goal was to have it be used by other packages.  It is also not too tight with Theano, except that most new features are made for Theano.
- Yes we would welcome external contributions.
- It won't ever be a drop-in replacement for NumPy since that is not a primary goal.  The goal is to have something functionally equivalent to NumPy, but on the GPU.  We probably won't ever support the full breadth of functionality that NumPy provides because there is so much of it and we have limited resources.
- It is not currently in the plans to ship pre-compiled functions.  That would also be difficult if you want to have specialized kernels for all possible devices.  However, it is in the plans to build an on-disk cache for kernels.  If such a thing is done, then pre-loading the cache (perhaps on install) would be a viable avenue.

**Comment by adler-j** [comment]
Thank you for the quick response, and with the satisfactory answers! The main question I have left is if you intend to merge the current `ndgpuarray` into `GpuArray` in some manner, to allow users the standard functionality of `+` etc?

**Comment by abergeron** [comment]
I'm not sure if it will be merged.

On one hand it would be slightly faster to have the functionality in C, but on the other hand, doing elementwise operations one by one is always going to be very slow on GPUs.  So it is almost always a better choice to build a specific kernel for what you need.

Also, there is the hurdle of generating kernels from C which is not super easy.

**Comment by adler-j** [comment]
Well for the average user, the step from writing x+y to compiling a cuda kernel is miles deep. Offering this step usually helps attracting new users. Then you can give them your nice "ElemwiseKernel" once they profile and realize that this is their performance bottleneck. Not to mention all the users you can attract by simply being a drop in replacement.

In many cases (notably tomography where we work), most of the time is generally spent doing some large matrix-vector like operations. Optimizing the vector-vector operations is usually ising on the cake then.

Regarding writing kernels i suppose som kind of cache would make this "fast enough" as is.

**Comment by abergeron** [comment]
The thing is for drop-in replacement there are a number of different options (like gnumpy) which will probably always be more complete and better support the full numpy API.  This is not a court we wish to play in.

Also, what is wrong with using the ndgpuarray class for most operations?  Maybe it could benefit from a bit more documentation exposure, but if having simple elemwise operations is important then you can use that.

There is currently an in-memory cache for kernels.  If we could augment that with an on-disk one, that would be almost perfect.  However I keep searching for code to do it for me and not finding it.  I may end up just writing it at some point.

**Comment by adler-j** [comment]
> The thing is for drop-in replacement there are a number of different options (like gnumpy) which will probably always be more complete and better support the full numpy API. This is not a court we wish to play in.

Valid point, but I honestly haven't found a library that is as simple and on point as yours while still containing the building blocks for the most important things (basically: indexing, arithmetic, ufuncs, broadcasting). gnumpy for example isn't maintained as a open source project, and seemingly the last update was 3 years ago. PyCUDA is quite monstrously large, and installation is complicated, specially on windows. I could go on :)

> Also, what is wrong with using the ndgpuarray class for most operations? Maybe it could benefit from a bit more documentation exposure, but if having simple elemwise operations is important then you can use that.

Mostly that it's not the default and hence will be chronically lagging in features and documentation :/ at least that's my experience. What we are looking for here is a way for users to access their data "like in numpy" that is simple to install yet has the basic things you'd expect. If I personally wanted to do this I could write the kernels, but our audience is mostly the math crowd and they are quite adverse to doing that.

> There is currently an in-memory cache for kernels. If we could augment that with an on-disk one, that would be almost perfect. However I keep searching for code to do it for me and not finding it. I may end up just writing it at some point.

Nice progress, current is probably quite enough for most cases, but storing on disk would be great!

**Comment by abergeron** [comment]
If you want to improve the support for numpy features in ndgpuarray, then I would certainly accept those PRs.  However, I don't have much time for make a numpy emulation library on top of this.

Also, all the features that ndgpuarray is lacking are also lacking in GpuArray.

**Comment by adler-j** [comment]
Ok, thanks for the clarification. Quite sure I have a better Idea of the goals, suppose we can close this issue now.

I'll try some libgpuarray integration and see how it works out!
