### ISSUE TITLE
Repeat init throws an error

### ISSUE THREAD

**Issue by adler-j** [Theano/libgpuarray#129]
If you call `pygpu.init` repeatedly you get an error:

```
pygpu.gpuarray.GpuArrayException: cannot set while device is active in this process: -1
```

this also applies if you at any point in the same process called `cudaSetDevice` from some other library. This is problematic since it interferes with using libgpuarray together with other cuda libraries. The simple fix is to simply ignore `cudaErrorSetOnActiveProcess`, as is done by other libraries [e.g. ASTRA](https://github.com/astra-toolbox/astra-toolbox/blob/3743fdc534b39958c105f4124ad1130d3e8b042a/cuda/3d/astra3d.cu#L420-L422).

**Comment by abergeron** [comment]
This was fixed by #140
