### ISSUE TITLE
UnboundLocalError in check_contig

### ISSUE THREAD

**Issue by adler-j** [Theano/libgpuarray#132]
The code [here](https://github.com/Theano/libgpuarray/blob/6d28fbf249e2fc8e842f7747e8a51ae1f872dd4a/pygpu/tools.py#L77-L81) can fail in case dims is not `None`, and `args.shape == dims` then we get:

```
UnboundLocalError: local variable 'n' referenced before assignment
```

This happened when I (by mistake) tried calling a kernel with a CPU array.

**Comment by abergeron** [comment]
You can probably copy the code here https://github.com/Theano/libgpuarray/blob/6d28fbf249e2fc8e842f7747e8a51ae1f872dd4a/pygpu/tools.py#L127-L129 to before the return in check_contig.

**Comment by abergeron** [comment]
The code in question is unused and will be removed so closing.
