### ISSUE TITLE
Build errors with MSVC

### ISSUE THREAD

**Issue by adler-j** [Theano/libgpuarray#134]
I'm getting some build errors with MSVC 2013, mostly related to using the inline keyword which is not supported by MSVC. I'll make a branch to fix these.

**Comment by nouiz** [comment]
thanks.

**Comment by abergeron** [comment]
We should `#define` inline to __inline for MSVC.

**Comment by adler-j** [comment]
Yeah I'm doing that

**Comment by nouiz** [comment]
It work now from what I know, so closing this old issue.
