### ISSUE TITLE
Optional context in ElemwiseKernel

### ISSUE THREAD

**Issue by adler-j** [Theano/libgpuarray#137]
Currently there is a default context, but it is not used by `ElemwiseKernel`. 

Perhaps we should make the context argument optional and attempt to use the default first?

**Comment by abergeron** [comment]
Do you mean the "set_default_context()" context?

If so, passing a context of `None` will make GpuKernel use the default.

However it is true that this is probably not documented or obvious in any way.

**Comment by adler-j** [comment]
That could work, but shouldnt it be an optional parameter then?

**Comment by abergeron** [comment]
Unfortunately we can't make the first parameter optional in python and I would be reluctant to change the order of parameters in order to not break existing code.

**Comment by adler-j** [comment]
Milestone: next breaking patch? :)

**Comment by adler-j** [comment]
Giving this a bump for a decision. Either reject and close, or add with a milestone.

**Comment by abergeron** [comment]
ElemwiseKernel is gone now.  So the issue is moot.
