### ISSUE TITLE
Cuda cache and GTX 970

### ISSUE THREAD

**Issue by adler-j** [Theano/libgpuarray#138]
The 970 card has two types of memory, 3.5 GB of fast memory and 0.5 GB slow, see for example [this article](http://www.pcgamer.com/why-nvidias-gtx-970-slows-down-using-more-than-35gb-vram/).

This causes issues with the libgpuarray cuda cache, since if a number of allocations is performed, we quickly reach the 3.5gb threshhold and then any extra memory will be in the remaining slow 0.5gb.

**Comment by abergeron** [comment]
If you want to disable the cache you can pass `disable_alloc_cache=True` to `pygpu.init()` when you create the context.

**Comment by adler-j** [comment]
> The allocation cache will reuse cached memory as soon as you need it. And if you go over 3.5 Gb it means that your problem needs that memory.

Did some napkin calculations and couldnt find how my program would reach 3.5 GB, but perhaps I need so search further. Is the cache smart if the allocations are mixed size? Consider:

Allocate `x`, 0.4 gb
Release `x`
Allocate `y`, 0.5 gb
Release `y`

Will 0.9 gb now be allocated?

> If you want to disable the cache you can pass disable_alloc_cache=True to pygpu.init() when you create the context.

Will try

**Comment by abergeron** [comment]
Growing sizes could lead to bad behaviour in the cache, yes.  I'm not sure how to avoid that.

However the other workaround for that is to allocate a big block at the start (say, 2Gb) and then free it immediately.  Then it will be split into pieces which will be recombined when you free and you shouldn't have problems with growing allocations.

**Comment by adler-j** [comment]
> Growing sizes could lead to bad behavior in the cache, yes. I'm not sure how to avoid that.

Indeed it is quite hard to handle, no idea here either.

> However the other workaround for that is to allocate a big block at the start (say, 2Gb) and then free it immediately. Then it will be split into pieces which will be recombined when you free and you shouldn't have problems with growing allocations.

Great idea, should work for me! Perhaps this could even be added as a parameter to `pygpu.init()`?

**Comment by nouiz** [comment]
On Wed, Mar 2, 2016 at 4:32 AM, Jonas Adler <notifications@github.com>
wrote:
[...]


> Great idea, should work for me! Perhaps this could even be added as a
> parameter to pygpu.init()?
>

We discussed that and I think it is the way to go. I also think we should
change the default to help prevent this. Maybe allocated 95% of the free
memory by default?

**Comment by adler-j** [comment]
Allocating too much will cause trouble, even opening a few figures after doing that could crash. I would actually personally make no cache the default since this is likely what people would expect.

**Comment by abergeron** [comment]
By "no cache" do you mean disable the cache? If so, I disagree because there is a big performance hit to allocating buffers on the GPU.  But we could allocate bigger blocks maybe to help bigger allocations.

Otherwise, I would also be against preallocating a large default since that would be quite unexpected.  I can however always add a parameter to make pygpu.init() preallocate a bunch of memory if desired.

**Comment by adler-j** [comment]
> By "no cache" do you mean disable the cache? If so, I disagree because there is a big performance hit to allocating buffers on the GPU. But we could allocate bigger blocks maybe to help bigger allocations.

Thats actually what I meant, but i respect if you dont like it, as long as you can pick which one.

> Otherwise, I would also be against preallocating a large default since that would be quite unexpected. I can however always add a parameter to make pygpu.init() preallocate a bunch of memory if desired.

That would be a great middle way! Perhaps also a "upper limit" to the cache size?

**Comment by abergeron** [comment]
If we integrate the preallocation in pygpu.init(), then it might be possible to also limit the size.  I'll see about that.

**Comment by abergeron** [comment]
Done for with 0.7
