### ISSUE TITLE
Unsupported kind: opencl

### ISSUE THREAD

**Issue by rayset** [Theano/libgpuarray#141]
I'm trying to run theano in gpu mode.

when I run the test at the end of this page:http://deeplearning.net/software/libgpuarray/installation.html 

i get the following error:

> python -c "import pygpu;pygpu.test()"
> pygpu is installed in /usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu
> NumPy version 1.10.4
> NumPy relaxed strides checking option: False
> NumPy is installed in /home/deep/.local/lib/python2.7/site-packages/numpy
> Python version 2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]
> nose version 1.3.6
> EEEEEE
> ======================================================================
> ERROR: Failure: RuntimeError (Unsupported kind: opencl)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_blas.py", line 4, in <module>
>     from .support import (guard_devsup, gen_gpuarray, context)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 34, in <module>
>     context = gpuarray.init(get_env_dev())
>   File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:8913)
>   File "pygpu/gpuarray.pyx", line 590, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8636)
>   File "pygpu/gpuarray.pyx", line 1025, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12842)
>   File "pygpu/gpuarray.pyx", line 519, in pygpu.gpuarray.get_ops (pygpu/gpuarray.c:7866)
> RuntimeError: Unsupported kind: opencl
> 
> ======================================================================
> ERROR: Failure: RuntimeError (Unsupported kind: opencl)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_elemwise.py", line 10, in <module>
>     from .support import (guard_devsup, rand, check_flags, check_meta, check_all,
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 34, in <module>
>     context = gpuarray.init(get_env_dev())
>   File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:8913)
>   File "pygpu/gpuarray.pyx", line 590, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8636)
>   File "pygpu/gpuarray.pyx", line 1025, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12842)
>   File "pygpu/gpuarray.pyx", line 519, in pygpu.gpuarray.get_ops (pygpu/gpuarray.c:7866)
> RuntimeError: Unsupported kind: opencl
> 
> ======================================================================
> ERROR: Failure: RuntimeError (Unsupported kind: opencl)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_gpu_ndarray.py", line 14, in <module>
>     from .support import (guard_devsup, check_meta, check_flags, check_all,
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 34, in <module>
>     context = gpuarray.init(get_env_dev())
>   File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:8913)
>   File "pygpu/gpuarray.pyx", line 590, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8636)
>   File "pygpu/gpuarray.pyx", line 1025, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12842)
>   File "pygpu/gpuarray.pyx", line 519, in pygpu.gpuarray.get_ops (pygpu/gpuarray.c:7866)
> RuntimeError: Unsupported kind: opencl
> 
> ======================================================================
> ERROR: Failure: RuntimeError (Unsupported kind: opencl)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_operations.py", line 4, in <module>
>     from .support import (gen_gpuarray, context)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 34, in <module>
>     context = gpuarray.init(get_env_dev())
>   File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:8913)
>   File "pygpu/gpuarray.pyx", line 590, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8636)
>   File "pygpu/gpuarray.pyx", line 1025, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12842)
>   File "pygpu/gpuarray.pyx", line 519, in pygpu.gpuarray.get_ops (pygpu/gpuarray.c:7866)
> RuntimeError: Unsupported kind: opencl
> 
> ======================================================================
> ERROR: Failure: RuntimeError (Unsupported kind: opencl)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_reduction.py", line 6, in <module>
>     from .support import (guard_devsup, check_meta_content, context, gen_gpuarray,
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 34, in <module>
>     context = gpuarray.init(get_env_dev())
>   File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:8913)
>   File "pygpu/gpuarray.pyx", line 590, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8636)
>   File "pygpu/gpuarray.pyx", line 1025, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12842)
>   File "pygpu/gpuarray.pyx", line 519, in pygpu.gpuarray.get_ops (pygpu/gpuarray.c:7866)
> RuntimeError: Unsupported kind: opencl
> 
> ======================================================================
> ERROR: Failure: RuntimeError (Unsupported kind: opencl)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
>     addr.filename, addr.module)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
>     return self.importFromDir(dir_path, fqname)
>   File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
>     mod = load_module(part_fqname, fh, filename, desc)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_tools.py", line 5, in <module>
>     from .support import (guard_devsup, rand, check_flags, check_meta, check_all,
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/support.py", line 34, in <module>
>     context = gpuarray.init(get_env_dev())
>   File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:8913)
>   File "pygpu/gpuarray.pyx", line 590, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8636)
>   File "pygpu/gpuarray.pyx", line 1025, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:12842)
>   File "pygpu/gpuarray.pyx", line 519, in pygpu.gpuarray.get_ops (pygpu/gpuarray.c:7866)
> RuntimeError: Unsupported kind: opencl
> 
> ----------------------------------------------------------------------
> Ran 6 tests in 0.002s
> 
> FAILED (errors=6)
> 

I do have opencl (clinfo shows my radeon 280x). what can I do?

**Comment by abergeron** [comment]
You must build libgpuarray with opencl.  It might not have built automatically because it wasn't detected.

**Comment by rayset** [comment]
thanks for the response.

do you know how can I check if it detects it? or by any chance how to make it detect fglrx? to install opencl I just gave apt-get install fglrx and fglrx-dev

**Comment by abergeron** [comment]
If you see something like

```
-- Could NOT find OpenCL
```
in the CMake configure step, then it didn't find OpenCL.

Otherwise it would print something like this:
```
-- Found OpenCL: /System/Library/Frameworks/OpenCL.framework
```
To help the CMake script find your install you can pass `-DOpenCL_LIBPATH=/your/install/path` to cmake.

You can also make a PR to add your path to the default searched list in CMakeModules/FindOpenCL.cmake if you feel up to it.

**Comment by rayset** [comment]
I realized that flgrx are just the drivers, so I installed the opencl sdk from this website:
http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/

the cmake step gives me indeed this error,

 -- Could NOT find OpenCL (missing:  OPENCL_INCLUDE_DIRS) 
 before installing the sdk it also gave ''missing: OPENCL_LIBRARY''

at this point I guess I'm missing a piece of opencl (I heard about headers?), do you perhaps have any idea? I don't have any file named ''OpenCL.framework'' in my pc (according to ubuntu's search). 
I don't have any clue of what those include dirs are.

Thank you again very much, you are very kind.

**Comment by abergeron** [comment]
The line I gave was just an example, you probably wont have the same path/file on your machine.  `.framework` files are mac-specific so on linux you should search for something like `libOpenCL.so`

For the headers look for `CL/cl.h`.

**Comment by rayset** [comment]
locate CL/cl.h
gives me
/usr/include/CL/cl.hpp
and
locate libOpenCL.so
gives
/usr/lib/libOpenCL.so

is the first one the include folder?

**Comment by rayset** [comment]
I read the source code for findopencl.make and I guess I found my problem.
The CL/cl.h is not in the standard ''/opt/AMDAPP/include" which do not exist on my machine, so I ran

find / -iname cl.h 2>/dev/null

and here it is: /home/deep/AMDAPPSDK-3.0/include/CL/cl.h

but running:
`
sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DOpenCL_LIBPATH=/home/deep/AMDAPPSDK-3.0/include/`

gives me this:

> 
> CUDA_TOOLKIT_ROOT_DIR not found or specified
> -- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
> -- Could NOT find OpenCL (missing:  OPENCL_INCLUDE_DIRS) 
> -- Configuring done
> -- Generating done
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     OpenCL_LIBPATH
> 
> 
> -- Build files have been written to: /home/deep/libgpuarray/build
> 
same with -DOpenCL_LIBPATH=/home/deep/AMDAPPSDK-3.0/include

**Comment by abergeron** [comment]
Try `OpenCL_INCPATH=/home/deep/AMDAPPSDK-3.0/include cmake .. -DCMAKE_BUILD_TYPE=Release`

This will hopefully work.

**Comment by rayset** [comment]
it kinda works!

after the test I get a lot of errors like this one:

> ======================================================================
> ERROR: pygpu.tests.test_blas.test_ger(4, 5, 'float32', 'c', -2, -2, False)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
>     self.test(*self.arg)
>   File "/usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg/pygpu/tests/test_blas.py", line 155, in ger
>     gr = gblas.ger(1.0, gX, gY, gA, overwrite_a=overwrite)
>   File "pygpu/blas.pyx", line 127, in pygpu.blas.ger (pygpu/blas.c:2907)
>   File "pygpu/blas.pyx", line 44, in pygpu.blas.pygpu_blas_rger (pygpu/blas.c:1655)
> GpuArrayException: ('Device does not support operation', 8)

and this as the final result:

Ran 12871 tests in 599.296s

FAILED (SKIP=536, errors=315)


is it normal? thank you so much for all the help you provided me.

**Comment by rayset** [comment]
uhm, running this code:

> from theano import function, config, shared, tensor, sandbox
> import numpy
> import time
> 
> vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
> iters = 1000
> 
> rng = numpy.random.RandomState(22)
> x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
> f = function([], tensor.exp(x))
> print(f.maker.fgraph.toposort())
> t0 = time.time()
> for i in range(iters):
>     r = f()
> t1 = time.time()
> print("Looping %d times took %f seconds" % (iters, t1 - t0))
> print("Result is %s" % (r,))
> if numpy.any([isinstance(x.op, tensor.Elemwise) and
>               ('Gpu' not in type(x.op).__name__)
>               for x in f.maker.fgraph.toposort()]):
>     print('Used the cpu')
> else:
>     print('Used the gpu')
it still gives me an error about how nvcc is not installed (but this is a cuda program...) and then uses the cpu. for some reason it seems theano still doesn't see gpuarray.

> ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.

this is my config file:
[global]
floatX = float32
device = gpu0
if I remove it it simply goes in cpu mode.

**Comment by abergeron** [comment]
For the pygpu tests failures this is normal if you don't have clBLAS installed, because there is no blas otherwise.  This will also mean that all the blas operations will stay on the CPU in theano (or fail, I'm not sure anymore).

Also be warned that the OpenCL support in Theano is experimental and lots of things don't work as they should.
