### ISSUE TITLE
conda package or Python wheel?

### ISSUE THREAD

**Issue by dwf** [Theano/libgpuarray#163]
Is libgpuarray now stable enough to consider putting up an official conda package for a release version?

**Comment by nouiz** [comment]
The master of Theano can't work with the dev version of libgpuarray. So we
would need to device some versioning that fix the version that Theano
support for correct depencies.

But having a conda install script would be useful I think.

Maybe in a few weeks we can have something more stable. There is a few
speed "regression" compared to current Theano gpu back-end that we need to
fix. I'm not sure if they will request interface change or not.

For the versioning, do you know which restriction we can have? Can you fix
version to 0.1.* ? Then when we break the interface we bump to 0.2.*? We
would just increase the * for new feature or speed up/bugfix.

On Wed, May 4, 2016 at 5:33 PM, David Warde-Farley <notifications@github.com

**Comment by jakirkham** [comment]
I'd be happy to help package `libgpuarray`. We would need to have a formal release to do so though. Honestly a git tag would be sufficient. Though we can probably try from a commit to see if there are needed tweaks before the release is cut. We just wouldn't be able to release the package until there is a source release.

**Comment by abergeron** [comment]
We now have a conda package that will soon be in the defaults channel.
