### ISSUE TITLE
Implement extcopy with GpuElemwise.

### ISSUE THREAD

**Issue by abergeron** [Theano/libgpuarray#169]
This should provide a nice speedup since it would benefit from dimension collapsing, addr32, and other things of the sort.

However to actually get that speedup we would need access to a per-context cache to avoid recompiling all the kernels everytime and this requires that we make a public context object to store these things.

**Comment by nouiz** [comment]
There is already a cache in the context for extcopy. Why not convert this
to an elemwise cache?

Actually, where is the cache for GpuElemwise in Theano? Inside that c
module?

**Comment by abergeron** [comment]
Because if we are going to use GpuElemwise for that I would move it out of backend-specific things.

In Theano we cache the GpuElemwise object in the thunk.

**Comment by abergeron** [comment]
This was done.
