### ISSUE TITLE
make error (cannot find libcuda.so file while it is in the intended path)

### ISSUE THREAD

**Issue by ashr59** [Theano/libgpuarray#171]
Hi,

I'm trying to install the pack based on [this recipe](http://blog.mdda.net/oss/2015/06/20/nvidia-on-fedora-22).

But make step generates these errors:
----------------------------------------------------------------------------------------------------------------------
[  1%] Generating ../../src/gpuarray_types.c, ../../src/gpuarray/types.h
Scanning dependencies of target gpuarray
[  3%] Building C object src/CMakeFiles/gpuarray.dir/cache/lru.c.o
[  5%] Building C object src/CMakeFiles/gpuarray.dir/cache/twoq.c.o
[  6%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_types.c.o
[  8%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_error.c.o
[ 10%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_util.c.o
[ 11%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer.c.o
[ 13%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array.c.o
[ 15%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array_blas.c.o
[ 16%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_kernel.c.o
[ 18%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_extension.c.o
[ 20%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_elemwise.c.o
[ 22%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_strl.c.o
[ 23%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.c.o
[ 25%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_blas_cuda_cublas.c.o
[ 27%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_opencl.c.o
[ 28%] Building C object src/CMakeFiles/gpuarray.dir/util/strb.c.o
[ 30%] Building C object src/CMakeFiles/gpuarray.dir/util/xxhash.c.o
make[2]: *** No rule to make target '/usr/lib64/nvidia/libcuda.so', needed by '../lib/libgpuarray.so'.  Stop.
CMakeFiles/Makefile2:89: recipe for target 'src/CMakeFiles/gpuarray.dir/all' failed
make[1]: *** [src/CMakeFiles/gpuarray.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

----------------------------------------------------------------------------------------------------------------------
When I try to locate libcuda.so there is no problem:

/usr/lib64/libcuda.so
/usr/lib64/libcuda.so.1
/usr/lib64/nvidia/libcuda.so
/usr/lib64/nvidia/libcuda.so.1
/usr/lib64/nvidia/libcuda.so.352.39
/usr/lib64/nvidia/libcuda.so.358.16

Any suggestion please?

**Comment by nouiz** [comment]
Can you give your solution? That way, if someone have the same problem in
the futur, they will find it faster.

thanks

**Comment by abergeron** [comment]
The solution is to not hardcode the wrong path to libcuda.so and let the cmake script find them.

**Comment by ashr59** [comment]
Yes, exactly. I had some not useful options in front of cmake command. Moreover, I was forced to reinstall my Fedora to solve all my strange problems which was not a reasonable solution for the others.

Thank you all,
Ali
