### ISSUE TITLE
New casting policies

### ISSUE THREAD

**Issue by nouiz** [Theano/libgpuarray#177]
- current not ideal
- max_floatX not ideal as in corner case of shape computation using float32 instead of float64 could cause less precission and wrong shape usage silently.
- python literal to mininum dtype not ideal as cause underflow as we don't always upcast the computation.

Proposal, python literal stay int64 float64, but we don't upcast computation between tensor (ndim >0) and scalar (ndim == 0).

Clean up old casting policies? Should we support both via a flag for a transition? It make this more complicated...

**Comment by abergeron** [comment]
I think that this should be an issue on Theano not libgpuarray.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/issues/4523 done
