### ISSUE TITLE
Error int64_t not defined with Visual Studio 2015

### ISSUE THREAD

**Issue by fx-kirin** [Theano/libgpuarray#180]
I compiled libgpuarray under Windows 7 x64 with Visual Studio 2015
I get errors `int64_t not defined`.

Then I modified gpuarray_buffer_opencl.c and add the following code. It fixed errors.
`#include <stdint.h>`

I just wanted to share the infomation and leave this issue.

**Comment by abergeron** [comment]
What include did you add?  Can you submit a PR?

**Comment by fx-kirin** [comment]
I'm not sure which file I should insert import command. But I'll submit a PR now.

**Comment by fx-kirin** [comment]
New version of libgpuarray seems to fix the bug.
