### ISSUE TITLE
xsplit tests fail due to empty arrays with different shapes

### ISSUE THREAD

**Issue by jkevin** [Theano/libgpuarray#184]
Tests for vsplit, hsplit and dsplit fail because of differences in the way empty arrays are handled. On one of the tests numpy 1.11 returns an array of shape (4,0) and pygpu returns a shape of (0,0).

**Comment by abergeron** [comment]
Yes because that was the old numpy behaviour.  We should move to the new one though.

**Comment by abergeron** [comment]
This now works with numpy 1.11.
