### ISSUE TITLE
Elemwise Composite/Switch not supported with OpenCL

### ISSUE THREAD

**Issue by githubnemo** [Theano/libgpuarray#189]
Just tested OpenCL (AMD/ATI) with Theano/libgpuarray from master (464bb9a) running a model implemented in Keras and got the following exception:

```
  File "blas.pyx", line 36, in pygpu.blas.pygpu_blas_rgemm (pygpu/blas.c:1512)
pygpu.gpuarray.GpuArrayException: ('Unsupported operation', 5)
Apply node that caused the error: GpuDot22(GpuElemwise{Composite{Switch(i0, (i1 + (i2 * i3)), i1)}}[]<gpuarray>.0, z1_W)
Toposort index: 736
Inputs types: [GpuArrayType<None>(float32, (False, False)), GpuArrayType<None>(float32, (False, False))]
Inputs shapes: [(128, 784), (784, 1000)]
Inputs strides: [(3136, 4), (4000, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuElemwise{add,no_inplace}(GpuDot22.0, InplaceGpuDimShuffle{x,0}.0)]]
```

With `optimizer=fast_compile`:

```
  File "blas.pyx", line 36, in pygpu.blas.pygpu_blas_rgemm (pygpu/blas.c:1512)
pygpu.gpuarray.GpuArrayException: ('Unsupported operation', 5)
Apply node that caused the error: GpuDot22(GpuElemwise{switch,no_inplace}.0, z1_W)
Toposort index: 550
Inputs types: [GpuArrayType<None>(float32, (False, False)), GpuArrayType<None>(float32, (False, False))]
Inputs shapes: [(128, 784), (784, 1000)]
Inputs strides: [(3136, 4), (4000, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuElemwise{add,no_inplace}(GpuDot22.0, GpuDimShuffle{x,0}.0)]]
```

I'm not sure if this a problem with the new `GpuElemwise` implementation or a missing kernel for OpenCL. Can I help?

**Comment by nouiz** [comment]
The OpenCL back-end is close to working. But we don't have use of it and don't have spare time to work on it. So we need people from the community to help finish it.

Are you ready to work on this?

This particular error is because you didn't install clBLAS, that provide the openCL blas. But you will with high probability get others problems after this one as we didn't finish everything.

**Comment by abergeron** [comment]
It's not the elemwise that had a problem, but the GpuDot22.  This means that you didn't compile libgpuarray with clBLAS, so there is no blas implementation on OpenCL.

Also, this would be more of a Theano issue than a libgpuarray one.
