### ISSUE TITLE
ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by marcoippolito** [Theano/libgpuarray#19]
Hi,
in Ubuntu 14.04 with Nvidia GeForce GTX 770, I installed via sudo apt-get http://packages.ubuntu.com/trusty/devel/nvidia-cuda-toolkit (5.5.22-3ubuntu1)
Followed the step-by-step-guide of libgpuarray: http://deeplearning.net/software/libgpuarray/installation.html#requirements

But when testing Theano with cuda, the output is:

marco@marco-All-Series:~/Theano-Testing$ THEANO_FLAGS=device=cuda0 python check1.py
ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/gpuarray/**init**.py", line 44, in <module>
    init_dev(config.device)
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/gpuarray/**init**.py", line 36, in init_dev
    context = pygpu.init(dev)
  File "gpuarray.pyx", line 575, in pygpu.gpuarray.init (pygpu/gpuarray.c:7317)
  File "gpuarray.pyx", line 546, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:7246)
  File "gpuarray.pyx", line 950, in pygpu.gpuarray.GpuContext.**cinit** (pygpu/gpuarray.c:10820)
GpuArrayException: No CUDA devices avaiable
[Elemwise{exp,no_inplace}(<TensorType(float64, vector)>)]
Looping 1000 times took 3.85683894157 seconds
Result is [ 1.23178032  1.61879341  1.52278065 ...,  2.20771815  2.29967753
  1.62323285]
Used the cpu

Any clues to solve the problem?

Looking forward to your kind hints.
Kind regards.
Marco

**Comment by fvisin** [comment]
I had a similar experience. In my case the apt-get installation did not load the required modules. 

I was able to solve the problem by running `sudo modprobe nvidia_331_updates nvidia-331-updates-uvm`. The modules that you need to load depend on your installation, one way to find them is to use the TAB-autocompletion, i.e., write `sudo modprobe nvidia` and press tab twice to see the list of nvidia modules available in your system.

**Comment by fccoelho** [comment]
I had the same problem but I got it solve by following the recommendation of @antimora :+1: 
I ran:
```shell
$ sudo theano-test #it detected gpu
$ chown -R <myusername> ~/.theano
$ theano-test # detected gpu!
```
thanks!

**Comment by nouiz** [comment]
@abergeron, what do you think of making a check in Theano that the
compiledir is owned by the user and if it isn't, raise an error by default?

I think it would help people understand more rapidly the problem.

What about the problem that when "sudo theano-test", the compiledir end up
being in the user home, not root home. Do one of you know why this can
happen?

**Comment by abergeron** [comment]
Because sudo changes the uid but not the rest of the environnement (especially $HOME)

**Comment by sjhddh** [comment]
Hey @abergeron @marcoippolito , Have you found the final solution?

I think I ran into a similar problem, 

I specified the issue here: #4384
[https://github.com/Theano/Theano/issues/4384#issuecomment-210933852](url)

Wish can get some ideas and help

Thank you

**Comment by nouiz** [comment]
It don't seem related to libgpuarray, so I replied in your original issue.
