### ISSUE TITLE
Python bindings build fails with Python2/3 and cython0.20.1

### ISSUE THREAD

**Issue by Quadrocube** [Theano/libgpuarray#194]
<pre>
ubuntu@master:~/libgpuarray$ python setup.py install                                                                                                                                                                                
Compiling pygpu/gpuarray.pyx because it changed.
Compiling pygpu/blas.pyx because it changed.
Compiling pygpu/_elemwise.pyx because it changed.
Cythonizing pygpu/_elemwise.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    cdef void **callbuf
    cdef unsigned int n

    def __cinit__(self, GpuContext ctx, expr, args, unsigned int nd=0,
                  preamble=b""):
        cdef gpuelemwise_arg *_args;
                                  ^
------------------------------------------------------------

pygpu/_elemwise.pyx:90:35: Syntax error in C variable declaration
Traceback (most recent call last):
  File "setup.py", line 110, in <module>
    ext_modules=cythonize(exts),
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 798, in cythonize
    cythonize_one(*args[1:])
  File "/usr/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 915, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pygpu/_elemwise.pyx
</pre>

Haven't played around much with cython, googling around didn't get any relevant results. Any help appreciated.
Ubuntu14.04, gpuarray installed OK

**Comment by abergeron** [comment]
This looks like the cython compile is using headers from an old version of the library.

**Comment by Quadrocube** [comment]
Thanks for participating, @abergeron!
I've installed Theano quite a while ago and still am a bit in a loss with all the variety of it's implicit dependencies. I'm currently trying to make it support float64 GPU optimizations and [found](https://groups.google.com/forum/#!topic/theano-users/uZwddVgMIkI) the proposition to install `libgpuarray` for this matter. I don't recall manually installing it previously though. 
Given that, can you point me at what can be done here?

**Comment by abergeron** [comment]
Did you install the C part of libgpuarray?

If not there are complete instructions here: http://deeplearning.net/software/libgpuarray/installation.html

**Comment by Quadrocube** [comment]
Yep. 
<pre>
[ 50%] Built target gpuarray
[100%] Built target gpuarray-static
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/include/gpuarray/array.h
-- Up-to-date: /usr/local/include/gpuarray/blas.h
-- Up-to-date: /usr/local/include/gpuarray/buffer.h
-- Up-to-date: /usr/local/include/gpuarray/buffer_blas.h
-- Up-to-date: /usr/local/include/gpuarray/config.h
-- Up-to-date: /usr/local/include/gpuarray/elemwise.h
-- Up-to-date: /usr/local/include/gpuarray/error.h
-- Up-to-date: /usr/local/include/gpuarray/extension.h
-- Up-to-date: /usr/local/include/gpuarray/ext_cuda.h
-- Up-to-date: /usr/local/include/gpuarray/kernel.h
-- Up-to-date: /usr/local/include/gpuarray/types.h
-- Up-to-date: /usr/local/include/gpuarray/util.h
-- Up-to-date: /usr/local/lib/libgpuarray.so
-- Up-to-date: /usr/local/lib/libgpuarray-static.a
</pre>
`ldconfig`'ed after that also. And after that am getting the error described at the header post

**Comment by abergeron** [comment]
Can you try a more recent version of cython?

**Comment by abergeron** [comment]
I just tried and it appears that 0.21 works and 0.20 fails.  I'll update the docs.

**Comment by Quadrocube** [comment]
Conforming, cython0.21 works fine. Thank you!
