### ISSUE TITLE
ielemwise2 broadcasting too overzealous?

### ISSUE THREAD

**Issue by davidweichiang** [Theano/libgpuarray#205]
If broadcast=True is set, ielemwise2 will not throw an exception if the output array has an axis with dimension 1 but the corresponding input array has dimension >1. Moreover, the result is not what I'd expect (below, I'd expect [6,9,12], but it is [5,7,9]).

```
import numpy
import pygpu

ctx = pygpu.init('cuda')
na = numpy.array([[1,2,3]])
ga = pygpu.array(na, context=ctx)
nb = numpy.array([[1,2,3],[4,5,6]])
gb = pygpu.array(nb, context=ctx)

try:
    na += nb
    print "this should not happen"
except:
    print "this should happen"

try:
    pygpu.elemwise.ielemwise2(ga, "+", gb, broadcast=True)
    print "this should not happen"
except:
    print "this should happen"
```

Output:

```
this should happen
this should not happen
```

**Comment by davidweichiang** [comment]
More specifically, I think it should be an error for a write argument to be broadcastable. However, check_basic doesn't know which arguments are write arguments, so I don't know how to implement the fix.

**Comment by nouiz** [comment]
Thanks for the report. I'm able to reproduce this. I label it as a bug.

**Comment by nouiz** [comment]
fixed. thanks for the report.
