### ISSUE TITLE
Use of GPU in Anaconda 2 not working (Windows 10)

### ISSUE THREAD

**Issue by dog56ui78** [Theano/libgpuarray#208]
I've followed the installation instructions for libgpuarray for windows but Theano still only uses the CPU in python 2.7/anaconda 2. I use the IDE pyCharm. Also I couldn't use CUDA as my GPU is Intel. I'm not sure if I'm missing something so here is what I did. Any help to fill in any holes or last steps is appreciated.

1. I installed cmake 3.6, Microsoft visual studio 2015, Microsoft Visual C++ Compiler for Python 2.7, CUDA 8, openCL runtime, clBLAS, mako, cython, theano (it works as far as i can tell), anaconda 2, pyCharm and python 2.7. The installations all seemed successful.
2. I used cmake on libgpuarray.git. It found openCL, CUDA, clBLAS. 
3. I built the ALL_BUILD sln file (release & debug) and it succeeded 4 times with no failures.
4. In cmd I navigated to the libgpuarray folder I placed in my %USERPROFILE% (current user)
dir
5. I ran the command (in the normal command prompt) python setup.py build, which was successful.
6. Ran python setup.py install which was also successful.
Also I am using the anaconda 2 project interpreter in pyCharm.

Do I need to make a .theanorc.txt file in %USERPROFILE% ? Because I made one with the contents:
[global]
floatX = float32
device = gpu

[nvcc]
flags=-LC:\Users\username\Anaconda2\libs
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

However with this python tries to use CUDA, which it can't because I dont have a NVIDIA GPU. Are there flags I am supposed to put in the file for python to use gpuarray?

Any help with figuring out if I missed a step or have to use a dif .theanorc file would be appreciated. Or should I uninstall CUDA? Thanks

Btw I am using the normal test found in the docs to test it. Theano runs on the cpu just fine.

**Comment by abergeron** [comment]
There are several things wrong with this:
- This is a support request for Theano, not libgpuarray
- If you don't have an NVIDIA GPU then installing CUDA is useless
- If you want to use libgpuarray in theano you can't use `device =  gpu` (Which is documented here: http://deeplearning.net/software/theano/tutorial/using_gpu.html#gpuarray-backend)
