### ISSUE TITLE
DLL load failed: The specified module could not be found for pygpu/libgpuarray

### ISSUE THREAD

**Issue by dog56ui78** [Theano/libgpuarray#209]
I'm using libgpuarray (openCL) but can't seem to get the GPU working with Theano in anaconda 2. When I try to run the test I get:

ERROR (theano.gpuarray): pygpu was configured but could not be imported
Traceback (most recent call last):
File "C:\Users\username\Anaconda2\lib\site-packages\theano-0.9.0.dev1-py2.7.egg\theano\gpuarray__init__.py", line 21, in
import pygpu
File "C:\Users\username\Anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg\pygpu__init__.py", line 7, in
from . import gpuarray, elemwise, reduction
ImportError: DLL load failed: The specified module could not be found.

Theano works fine with the cpu. I ran the command code "python setup.py build" and "python setup.py install" on setup.py in the libgpuarray folder (after I used cmake to install libgpuarray) to get pygpu and it ran successfully. After running cmake I get the gpuarray.dll file yet this error still occurs. Do I need to do something with it or is there something else happening?

**Comment by JonnoFTW** [comment]
You need to make sure python can find your `.dll` files. Try copying them to the dll folder of your anaconda install.

**Comment by abergeron** [comment]
Can you list the files in `C:\Users\username\Anaconda2\lib\site-packages\theano-0.9.0.dev1-py2.7.egg\theano\gpuarray\`

**Comment by abergeron** [comment]
Since there have been no news, I will assume the problem is fixed.

**Comment by hash** [comment]
Hi @abergeron .

I have the same issue. 

> python -c "import theano"
> ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)
> NoneType: None

> python -c "import pygpu"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\hash\Miniconda3\lib\site-packages\pygpu\__init__.py", line 7, in <module>
>     from . import gpuarray, elemwise, reduction
> ImportError: DLL load failed: The specified procedure could not be found.

I have "C:\Users\hash\Miniconda3\Lib\site-packages\Theano-0.9.0.dist-info" with:

- DESCRIPTION.rst
- entry_points.txt
- INSTALLER
- METADATA
- metadata.json
- RECORD
- top_level.txt
- WHEEL

and "C:\Users\hash\Miniconda3\Lib\site-packages\theano\gpuarray" with:

- basic_ops.py
- blas.py
- blockgemv.c
- blockger.c
- blocksparse.py
- conv_desc.c
- corr3d_gemm.c
- corr_gemm.c
- cudnn_helper.h
- dnn.py
- dnn_base.c
- dnn_batchnorm.c
- dnn_batchnorm_base.c
- dnn_batchnorm_grad.c
- dnn_batchnorm_inf.c
- dnn_conv_base.c
- dnn_dropout_desc.c
- dnn_dropout_fwd.c
- dnn_fwd.c
- dnn_gi.c
- dnn_gw.c
- dnn_pool.c
- dnn_pool_grad.c
- dnn_rnn_desc.c
- dnn_rnn_fwd.c
- dnn_rnn_gi.c
- dnn_rnn_gw.c
- dnn_rnn_paramsize.c
- dnn_softmax.c
- dnn_softmax_grad.c
- elemwise.py
- extra_ops.py
- fft.py
- fp16_help.py
- gemm16.c
- gpuarray_helper.h
- kernel_codegen.py
- linalg.py
- multinomial.py
- neighbours.py
- nerv.py
- nnet.py
- opt.py
- opt_util.py
- pool.c
- pool.py
- pool_ave_grad.c
- pool_grad_grad.c
- pool_max_grad.c
- pool_max_rop.c
- reduction.py
- subtensor.py
- tests\
- type.py
- _ _ init _ _.py
- _ _ pycache _ _\

.theanorc: 

> [global]
> floatX = float32
> device = cuda
> 
> [nvcc]
> flags=-LC:\Users\hash\Miniconda3\libs
> compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
