### ISSUE TITLE
pygpu.test() hungup

### ISSUE THREAD

**Issue by NeutralCode** [Theano/libgpuarray#211]
I compiled libgpuarray and pygpu, then do pygpu.test().
It was hanged up.

[Environment]
Windows8.1 PRO x64
OpenCL(Tonga)
gpuarray compiled from source by VisualStudio2015
anaconda3-4.1.1, conda create python=3.4.4 anaconda libpython mingw
pygpu setup from source by WindowsSDK7.1(with --compiler=msvc)

Compiling with debug option and do it again, the problem occurs around gpuarray.pyx L995.
>            try:
>                res = tmp.decode('ascii')
>            finally:
>                free(tmp)  # here

I changed it  to follows. (I change that  to don't free)
>                res = tmp.decode('ascii')

Then, the error didn't occur.

**Comment by abergeron** [comment]
This may help you but it will leak memory since the returned string is allocated.

Try to run the tests passing verbosity=10 to see if anything more shows up that could help.

**Comment by NeutralCode** [comment]
Thank you your advise.

I was heartened by you, I found the reason.
It's missmatch of compiler between gpuarray.dll (compiled by VisualStudio2015) and pygpu(compiled by Windows SDK 7.1).
