### ISSUE TITLE
Wrong major API version for gpuarray

### ISSUE THREAD

**Issue by fancyerii** [Theano/libgpuarray#213]
I installed theano 0.8.2 in ubuntu 14.04. tried both libgpuarray-v-9998 and lastest master of libgpuarray. Cuda version 7.5 and pygpu-0.2.1.

$ THEANO_FLAGS="contexts=dev0->cuda0;dev1->cuda1" python -c 'import theano'
Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN 5004)
ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/lli/venv-theano/local/lib/python2.7/site-packages/theano/sandbox/gpuarray/**init**.py", line 109, in <module>
    init_dev(d.strip(), n.strip())
  File "/home/lli/venv-theano/local/lib/python2.7/site-packages/theano/sandbox/gpuarray/**init**.py", line 46, in init_dev
    "Make sure Theano and libgpuarray/pygpu "
RuntimeError: ('Wrong major API version for gpuarray:', -9998, 'Make sure Theano and libgpuarray/pygpu are in sync.')

**Comment by nouiz** [comment]
With the new back-end, you should use the dev version of libgpuarray and
Theano.

I don't recommand Theano 0.8.2 with the new back-end. There is too much
update to the code.

**Comment by david-berthelot** [comment]
I'm getting the same error, except that libgpuarray is now version -9997.

- Theano 0.8.2
- Cuda 7.5
- CuDNN 5.0

If I patch the init_dev to ignore the major version, I get another error down the line:

> AssertionError: cuDNN optimization was enabled, but Theano was not able to use it for context dev1. We got this error: 
> Not on a CUDA device.

When is this going to work or is multiple gpu support not widely used and should not be counted on?

**Comment by slefrancois** [comment]
As stated earlier, we would recommend you install the development version of Theano. A lot of updates regarding the new gpuarray backend support have been added since the release.

You can also make sure that you have installed matching version of CUDA, the nvidia driver and CuDNN packages.

**Comment by nouiz** [comment]
Closing. We redid the versioning: https://github.com/Theano/libgpuarray/pull/323
