### ISSUE TITLE
Should we swap gdim and ldim?

### ISSUE THREAD

**Issue by nouiz** [Theano/libgpuarray#248]
GpuKernel_call take as param:
err = GpuKernel_call(&k_k, 1, &ls, &gs, 0, args);

Where the order ls followed by gs come from? Is that the order in OpenCL? In Theano, a call mechanism use the order gs, ls: https://github.com/Theano/Theano/pull/4925. Ideally, we should harmonize this.

This is the CUDA order.

**Comment by abergeron** [comment]
I just checked and it's `gs, ls` in OpenCL too.  So I guess we can swap this, but it's a lot of work (meaning there are lots of places to change) and error-prone since none of the argument types change.

**Comment by nouiz** [comment]
IRL discussion with @abergeron resume.

error-prone, but not too much. We can grep for a few function call in
Theano and libgpuarray and fix them. We will need to bump the major version
number to make sure compitible pair of Theano and libgpuarray are used. It
will help detect problem if other project used those interface.

**Comment by nouiz** [comment]
done
