### ISSUE TITLE
Memory allocation with Theano

### ISSUE THREAD

**Issue by jessejohns** [Theano/libgpuarray#255]
Hello,

I think this is the appropriate place to put this ticket... I apologize in advance if that's not the case.

I have 4 GTX 1080s, but I am just trying to test two right now.  So, each device has 8GB of memory.

When using multiple GPUs, the preallocate flag seems to not work correctly.  For example, if I set preallocate = 1.0 (lets make it easy), rather than allocate 8GB on each device, libgpuarray attempts to allocate 16GB to the first device and then 8GB to the second device.  If I set, preallocate = .5, then 8GB is set to the first device and 4 GB to the second device.

It seems like (number of devices) x (amount of memory per device) x (preallocate factor) is being set to the first device and (amount of memory per device) x (preallocate factor) is being set to the second device.

**Comment by jessejohns** [comment]
Update:

I tried with four devices, the first device always get 2X the amount of memory that should be allocated.  All other devices are appropriately allocated.

**Comment by abergeron** [comment]
This should be a Theano question, from what I read and possibly a mailing-list question.

However, which flags exactly are you using and what is the exact output from Theano?
Can you post the nvidia-smi results?

**Comment by jessejohns** [comment]
```
[global]
floatX = float32
device = cuda
contexts = dev0->cuda0;dev1->cuda1

[cuda]
root = /usr/local/cuda

[nvcc]
fastmath = True

[gpuarray]
preallocate = 0.4
```

```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.27                 Driver Version: 367.27                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:02:00.0      On |                  N/A |
| 27%   38C    P2    38W / 180W |   6653MiB /  8105MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:03:00.0     Off |                  N/A |
| 27%   35C    P2    36W / 180W |   3360MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 0000:82:00.0     Off |                  N/A |
| 27%   33C    P8     9W / 180W |      3MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 0000:83:00.0     Off |                  N/A |
| 27%   36C    P8     9W / 180W |      3MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1845    G   /usr/lib/xorg/Xorg                              50MiB |
|    0     31696    C   python                                        6599MiB |
|    1     31696    C   python                                        3357MiB |
+-----------------------------------------------------------------------------+

```

**Comment by jessejohns** [comment]
I believe this is because it first maps memory to cuda0, then again to cuda0, and cuda1.  I suspect I'm not appropriately using the multiGPU feature.  I'll go ahead and close.

**Comment by abergeron** [comment]
I get why it does double allocation on cuda0.  It is because it is referred to by two different names ('cuda' and 'cuda0') and because of that Theano thinks it's actually two different devices.  If you use 'device=cuda0' instead the problem will go away because Theano will realize that a device is shared.

Also, yes, in the second case, you don't have a default device and everything not explicitly mapped to a GPU will go on the CPU.

**Comment by jessejohns** [comment]
I got the same behavior as @theano-bot , but when I didn't specify device=*, I would not be able to compile.  So, the following as suggested by @abergeron:

`THEANO_FLAGS="device=cuda0,contexts=dev0->cuda0;dev1-> cuda1,gpuarray.preallocate=0.9`

I get the following behavior:

Using Thean```
o backend.
Preallocating 7302/8113 Mb (0.900000) on cuda0
Mapped name None to device cuda0: GeForce GTX 1080
Using cuDNN version 5105 on context None
Mapped name dev0 to device cuda0: GeForce GTX 1080
Using cuDNN version 5105 on context dev0
Preallocating 7302/8113 Mb (0.900000) on cuda1
Mapped name dev1 to device cuda1: GeForce GTX 1080
Using cuDNN version 5105 on context dev1

```
memory is properly allocated.
