### ISSUE TITLE
Crash when executing context.devname

### ISSUE THREAD

**Issue by dkit** [Theano/libgpuarray#257]
I'm using windows 10.

After installing libgpuarray, the tests kept crashing. I was able to trace the issue to:

free(__pyx_v_tmp);
in function __pyx_pf_5pygpu_8gpuarray_10GpuContext_7devname___get__ in gpuarray.c .

I know __pyx_v_tmp is a valid c string of 256 bytes, so I'm not sure why freeing it causes a crash... Removing that line and recompiling allows "most" of the tests to execute.

Also found that free(__pyx_v_self->ga.dimensions); and free(__pyx_v_self->ga.strides); in __pyx_pf_5pygpu_8gpuarray_8GpuArray_5shape_2__set__ also crashed python. 

These crashes happen at the application of the free function.

**Comment by abergeron** [comment]
You are using mixed C runtimes, which is a common problem on Windows for python C extensions.

You have to make sure to build everything with the same compiler version.  The compiler version to use depends on the version of python you are using.

**Comment by dkit** [comment]
Thank you. That was the issue. I was using Visual Studio for Python 9.0 compiler for the extension, but VS 2013 for everything else. Using a single compiler fixed the issue.
