### ISSUE TITLE
Make fails on Ubuntu 16.04, GCC 5 due to check

### ISSUE THREAD

**Issue by gokul-uf** [Theano/libgpuarray#260]
I had installed check via `apt-get`, I get the following output when I try installing libgpuarray

```
gokul@gokstudio:~$ cd libgpuarray/Build/
gokul@gokstudio:~/libgpuarray/Build$ make
[ 33%] Built target gpuarray
[ 67%] Built target gpuarray-static
[ 69%] Linking C executable check_elemwise
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_log.o): In function `subunit_lfun':
(.text+0x5f4): undefined reference to `subunit_test_start'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_log.o): In function `subunit_lfun':
(.text+0x6bf): undefined reference to `subunit_test_fail'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_log.o): In function `subunit_lfun':
(.text+0x6d4): undefined reference to `subunit_test_pass'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcheck_pic.a(check_log.o): In function `subunit_lfun':
(.text+0x6ef): undefined reference to `subunit_test_error'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/check_elemwise.dir/build.make:151: recipe for target 'tests/check_elemwise' failed
make[2]: *** [tests/check_elemwise] Error 1
CMakeFiles/Makefile2:209: recipe for target 'tests/CMakeFiles/check_elemwise.dir/all' failed
make[1]: *** [tests/CMakeFiles/check_elemwise.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

This is a problem with check on 16.04 as mentioned here
https://github.com/libcheck/check/issues/60
The linker flag needs to be changed. I would like to help with this, how should I go about this?

**Comment by abergeron** [comment]
That's weird, since I do have 16.04 and I can compile with libcheck correctly.  However I do have gcc 4.9 instead of 5.  Maybe that's part of the problem.

**Comment by abergeron** [comment]
Actually I just tried with gcc 5.4.0 and it works.  Can you try to remove the Build directory and try again?

**Comment by Sentient07** [comment]
The same happened for me when I tried to upgrade my GCC and CUDA( I faced problem stating absence of check and gfortran). You have to reinstall the GCC and link it again.
BTW, for me, building GCC took 32min, but after that, this problem of building was solved

**Comment by abergeron** [comment]
I just want to note that I didn't do any building of GCC.  I just installed from the official ubuntu packages and switched versions using update-alternatives.

**Comment by Sentient07** [comment]
> I just want to note that I didn't do any building of GCC. I just installed from the official ubuntu packages and switched versions using update-alternatives.

Even I installed from brew using `brew install gcc`. It took me longer time than what I expected and hence thought there was some problem and did found [this](http://stackoverflow.com/questions/18038764/can-not-brew-install-gcc48-on-mac). In the answers, they say build time and hence i said build :)

**Comment by abergeron** [comment]
@Sentient07 If you are on a mac, don't use gcc.  Use clang that comes with Xcode.

@gokul-uf here is on Ubuntu (or some other linux distribution which uses apt) and therefore should use gcc.
