### ISSUE TITLE
Error with reshape

### ISSUE THREAD

**Issue by MaximumEntropy** [Theano/libgpuarray#277]
Hi,

I encountered this array while trying to reshape a tensor when implementing a bidirectional RNN.

x = tensor.matrix('x', dtype='int64')
xr = x[::-1, :]
n_timesteps = x.shape[0]
n_samples = x.shape[1]
print n_timesteps, n_samples
emb = emb[x.flatten()]
print 'emb', emb.eval({x:numpy.random.randint(low=0, high=20, size=(32, 1))}).shape
emb = emb.reshape([n_timesteps, n_samples, options['dim_word_src']])
print 'emb', emb.eval({x:numpy.random.randint(low=0, high=20, size=(32, 1))}).shape
embr = emb[xr.flatten()]
print 'embr', embr.eval({x:numpy.random.randint(low=0, high=20, size=(32, 1))}).shape
embr = embr.reshape([n_timesteps, n_samples, options['dim_word_src']])
print 'embr', embr.eval({x:numpy.random.randint(low=0, high=20, size=(32, 1))}).shape # breaks here!

It breaks on the last eval with the following error:

RuntimeError: Invalid value or operation
Apply node that caused the error: GpuAdvancedSubtensor1(Wemb, GpuReshape{1}.0)
Toposort index: 6
Inputs types: [GpuArrayType<None>(float32, (False, False)), GpuArrayType<None>(int64, (False,))]
Inputs shapes: [(30000, 512), (32,)]
Inputs strides: [(2048, 4), (-8,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuReshape{3}(GpuAdvancedSubtensor1.0, MakeVector{dtype='int64'}.0)]]

**It doesn't happen on the old backend.**

**Comment by nouiz** [comment]
I think we fixed stuff related to reshape, so I'll close. If you still have problems, tell us.

**Comment by ozancaglayan** [comment]
With the latest libgpuarray and Theano from git, I still have this error with my code having a similar reshape in the RNN part:

```
RuntimeError: Invalid value or operation
Apply node that caused the error: GpuAdvancedSubtensor1(Wemb_enc, GpuReshape{1}.0)
Toposort index: 347
Inputs types: [GpuArrayType<None>(float32, (False, False)), GpuArrayType<None>(int64, (False,))]
Inputs shapes: [(8530, 100), (39,)]
Inputs strides: [(400, 4), (-8,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuElemwise{Composite{Switch(i0, (i1 * i2 * i3), i2)}}[]<gpuarray>(InplaceGpuDimShuffle{x,x}.0, GpuArrayConstant{[[ 1.25]]}, GpuAdvancedSubtensor1.0, GpuElemwise{Composite{Cast{float32}(LT(i0, i1))}}[]<gpuarray>.0)]]
```

**Comment by ozancaglayan** [comment]
Here's a self contained version which fails on the last function `f4` for gpuarray backend:

```
#!/usr/bin/env python

import theano
from theano import tensor
import numpy

dim_word_src = 16
n_vocab = 200
embs = numpy.random.rand(n_vocab, dim_word_src).astype('float32')
xx = numpy.random.randint(low=0, high=200, size=(32,1))

##
x = tensor.matrix('x', dtype='int64')
emb = tensor.matrix('emb', dtype='float32')
n_timesteps = x.shape[0]
n_samples = x.shape[1]

f1 = theano.function([emb, x], emb[x.flatten()])
print f1(embs, xx).shape

f2 = theano.function([emb, x], emb[x.flatten()].reshape([n_timesteps, n_samples, dim_word_src]))
print f2(embs, xx).shape

f3 = theano.function([emb, x], emb[x[::-1, :].flatten()])
print f3(embs, xx).shape

# gpuarray fails on this one
f4 = theano.function([emb, x], emb[x[::-1, :].flatten()].reshape([n_timesteps, n_samples, dim_word_src]))
print f4(embs, xx).shape
```
