### ISSUE TITLE
Missing module gpuarray.

### ISSUE THREAD

**Issue by DennisLiu94** [Theano/libgpuarray#278]
Hi all,
I tried to install pygpu on my gpu server to run platoon.

The environment is Ubuntu 16.04, cuda 8.0, gcc 4.8 and K80 cards. NCCL has been installed correctly.

After following the instructions to compile and install the package with sudo into default locations, this error occurs when pygpu is imported.

>>>import pygpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
  File "pygpu/elemwise.py", line 3, in <module>
    from .dtypes import dtype_to_ctype, get_common_dtype
  File "pygpu/dtypes.py", line 6, in <module>
    from . import gpuarray
ImportError: cannot import name gpuarray

and when 

>>>import gpuarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gpuarray

Any idea?
Thanks a lot.

**Comment by nouiz** [comment]
There is 2 step in installing libgpuarray.

1) Install the c library
2) Install the pygpu wrapper.

Did you do both?

If so, change your current working directory, it would be that it import
from the git cloned version and not the compiled/installed version.
