### ISSUE TITLE
ga_double, ga_byte : Is libgpuarray the authority?

### ISSUE THREAD

**Issue by mdda** [Theano/libgpuarray#29]
I'm asking because ```Theano/theano/sandbox/gpuarray/elemwise.py``` also includes these in its preamble, and they appear to be the CUDA versions only.  (I know I should also ask in the Theano issues, but I figure I could start here...)

Also, I think that libgpuarray's list could be checked vs the equivalent in ```/usr/include/CL/cl_platform.h``` (or whatever is equivalent on your system), since OpenCL device-independent types are set out there too.  eg: rather than libgpuarray defining ```ga_byte``` for OpenCL platforms independently (to ```char```), perhaps it should define it as being ```int8_t``` (for example), or ```cl_char``` (for clarity).

**Comment by abergeron** [comment]
This is just to note that multi-gpu support is finally in (about a year late).  So if you feel like working on this again, now would be a good time :)
