### ISSUE TITLE
Bool of gpuarray need fixing

### ISSUE THREAD

**Issue by nouiz** [Theano/libgpuarray#295]
https://github.com/Theano/Theano/issues/5252#issuecomment-261609228

gpuarray don't always evaludate to to the same True/False as numpy ndarray. See the issue above. We need to fix this.

**Comment by nouiz** [comment]
Also, if there is more then 1 value, we need to raise the same error as numpy.

**Comment by abergeron** [comment]
I wouldn't say this is a bug, but rather an enhancement.

**Comment by nouiz** [comment]
One of the goal of libgpuarray/pygpu is to be able to replace numpy with an object on the gpu having:

if gpuarray(0):

take the true branch is a bug in that sence. We are telling people it is an ndarray on the GPU and we don't do that there and this cause wrong result compared to that we told. If we where always raising an error in that case, then adding the support would be an enhancement.

Anyway, this is just words, we agree we should do it :)

**Comment by nouiz** [comment]
fixed.
