### ISSUE TITLE
GpuElemwise fails for "uneven broadcasts"

### ISSUE THREAD

**Issue by kohr-h** [Theano/libgpuarray#296]
I'm not sure if that is intended use of broadcasting, but `GpuElemwise` fails if I try to compute `out <-- a * x + b * out` where `out` and `x` have shape `(10, 10)`, `a` has shape `(10, 1)` and `b` is a scalar. See [this gist](https://gist.github.com/kohr-h/1d77c030aae32c8665eaf5908774767c) for a full example.

It's a bit hard for me to tell if I'm using the class correctly since the only thing I did basically was look a the code of the `ielemwise2` function and try to generalize it. Help is welcome.

**Comment by abergeron** [comment]
Your code is correct, but there was a bug in the underlying C code which I just fixed: #297.

Thank you for the report and the easy-to-use test case.

**Comment by kohr-h** [comment]
Nice! Thanks for the quick reply.

**Comment by kohr-h** [comment]
Code works for my case.

**Comment by nouiz** [comment]
fixed.
