### ISSUE TITLE
python2.7 and opencl

### ISSUE THREAD

**Issue by flare04** [Theano/libgpuarray#310]
I believe I have followed the instructions to compile and install everything on CentOS 7.2, python 2.7, cmake 3 gcc version 4.8.5 pyopencl (2016.2) pygpu (0.6.0rc1)

ls -l /usr/lib64/python2.7/site-packages/pygpu-0.6.0rc1-py2.7-linux-x86_64.egg/pygpu/
total 2812
-rw-rw-r--. 1 root root     835 Dec  8 11:46 __init__.py
-rw-rw-r--. 1 root root    1708 Dec  8 11:46 __init__.pyc
-rw-rw-r--. 1 root root   10304 Dec  8 11:46 _array.py
-rw-rw-r--. 1 root root   13718 Dec  8 11:46 _array.pyc
-rw-rw-r--. 1 root root     285 Dec  8 11:46 _elemwise.py
-rw-rw-r--. 1 root root     633 Dec  8 11:46 _elemwise.pyc
-rwxr-xr-x. 1 root root  212253 Dec  8 11:46 _elemwise.so
-rw-rw-r--. 1 root root     280 Dec  8 11:46 blas.py
-rw-rw-r--. 1 root root     618 Dec  8 11:46 blas.pyc
-rwxr-xr-x. 1 root root  196051 Dec  8 11:46 blas.so
-rw-rw-r--. 1 root root    4534 Dec  8 11:46 blas_api.h
-rw-rw-r--. 1 root root    1332 Dec  8 11:46 collectives.h
-rw-rw-r--. 1 root root     287 Dec  8 11:46 collectives.py
-rw-rw-r--. 1 root root     639 Dec  8 11:46 collectives.pyc
-rwxr-xr-x. 1 root root  810420 Dec  8 11:46 collectives.so
-rw-rw-r--. 1 root root    7273 Dec  8 11:46 collectives_api.h
-rw-rw-r--. 1 root root    6739 Dec  8 11:46 dtypes.py
-rw-rw-r--. 1 root root    7290 Dec  8 11:46 dtypes.pyc
-rw-rw-r--. 1 root root    3167 Dec  8 11:46 elemwise.py
-rw-rw-r--. 1 root root    4170 Dec  8 11:46 elemwise.pyc
-rw-rw-r--. 1 root root    1961 Dec  8 11:46 gpuarray.h
-rw-rw-r--. 1 root root     284 Dec  8 11:46 gpuarray.py
-rw-rw-r--. 1 root root     630 Dec  8 11:46 gpuarray.pyc
-rwxr-xr-x. 1 root root 1440206 Dec  8 11:46 gpuarray.so
-rw-rw-r--. 1 root root   13621 Dec  8 11:46 gpuarray_api.h
-rw-rw-r--. 1 root root     808 Dec  8 11:46 numpy_compat.h
-rw-rw-r--. 1 root root    4050 Dec  8 11:46 operations.py
-rw-rw-r--. 1 root root    5600 Dec  8 11:46 operations.pyc
-rw-rw-r--. 1 root root    9926 Dec  8 11:46 reduction.py
-rw-rw-r--. 1 root root   10864 Dec  8 11:46 reduction.pyc
drwxrwxr-x. 2 root root    4096 Dec  8 11:46 tests
-rw-rw-r--. 1 root root    8490 Dec  8 11:46 tools.py
-rw-rw-r--. 1 root root   11515 Dec  8 11:46 tools.pyc
-rw-rw-r--. 1 root root     100 Dec  8 11:46 version.py
-rw-rw-r--. 1 root root     302 Dec  8 11:46 version.pyc

python -c "import pygpu;pygpu.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
  File "pygpu/elemwise.py", line 3, in <module>
    from .dtypes import dtype_to_ctype, get_common_dtype
  File "pygpu/dtypes.py", line 6, in <module>
    from . import gpuarray
ImportError: cannot import name gpuarray

Any ideas would be appreciated ?

**Comment by abergeron** [comment]
Try running `sudo ldconfig`

**Comment by flare04** [comment]
ldconfig -v | grep -i gpu
libgpuarray.so.0.1 -> libgpuarray.so.0.1

It seems to be known by ldconfig

**Comment by nouiz** [comment]
Just a note, our opencl back-end is missing features in Theano. So if you
planed to use it with Theano, don't be surprised that many ops are missing.

Also, after installation, you should not run that command in the
libgpuarray directories.

**Comment by abergeron** [comment]
I find it weird that ldconfig does not have an absolute path to the library.

Otherwise, can you try and determine exactly why python can't import gpuarray.so.  It should either be because the module can't be found or because a dependant library can't be loaded.

You can try to run ldd on gpuarray.so to make sure all the required libraries are found.  You can also try to run `python -v -c 'import pygpu'` to attempt to get more information as to why it can't import gpuarray.

**Comment by abergeron** [comment]
Since this doesn't have any more news and there is nobody else that has this problem, I'm closing this.  If you have more info on the ticket, please reopen or create a new one.
