### ISSUE TITLE
Unable to install pygpu after recent rebase

### ISSUE THREAD

**Issue by Sentient07** [Theano/libgpuarray#315]
I rebased my work on a PR in theano to current master this evening (CET). Later when I tried testing the new backend, I was asked to reinstall pygpu as I was using an older version. I pulled from the master of `libgpuarray`, then built it using `cmake` and `make` and then tried building pygpu using `python setup.py build`. It gave me following errors, http://pastebin.com/9gzeP4ra
More details, 
I use OSX 10.12 with Xcode 7.3, CLT for XCode 7.3 and clang configured with LLVM 7.3.0. My GPU is Nvidia 750M and I use CUDA toolkit 8 with cuDNN 5105.

**Comment by nouiz** [comment]
You probably are mixing libgpuarray version. Make sure to remove the installed version and delete all build directory and recompile.

**Comment by Sentient07** [comment]
Tried that already. It doesn't work. The problem is actually with compiling `libgpuarray` I suppose. When I do `make test` inside the Build directory, I get errors. The traceback( looks like a condensed version) http://pastebin.com/ub9ipzqP

**Comment by Sentient07** [comment]
I got what was going wrong. When you do `make install` it exits without any errors, but fails to copy header files to `/usr/local/include/gpuarray/array.h`. But I clearly remember it worked before without elevating permission. We need to modify this in the doc, I think.

**Comment by Sentient07** [comment]
Elevating permissions of the current user when using the default installation path fixes it
