### ISSUE TITLE
Computations on float16 arrays produce garbage

### ISSUE THREAD

**Issue by kohr-h** [Theano/libgpuarray#316]
Probably related to #218:
```python
>>> a_h = np.ones((2, 3, 4), dtype='float16')
>>> a_d = pygpu.array(a_h, dtype='float16')
>>> reduce1(a_d, op='+', neutral=0, out_type='float16', axis=None)
gpuarray.array(-0.0078125, dtype=float16)
```
There's no option to convert float16 here, but the underlying GpuKernel defaults to `have_half=False` and that flag is not changed in `ReductionKernel` as far as I can see.

Reference:

[Half-precision arithmetic supported for "Pascal" architectures and upward](https://devblogs.nvidia.com/parallelforall/mixed-precision-programming-cuda-8/) (see section "Mixed Precision Performance on Pascal GPUs"; probably CUDA 8 required)

Edit: Forgot to mention that I have a Kepler GPU.

**Comment by kohr-h** [comment]
Actually, the error already happens in conversion from float16 without any computation otherwise:
```python
>>> a_h = np.ones((2, 2), dtype='float16')
>>> a_d = pygpu.array(a_h, dtype='float16')
>>> a_d
gpuarray.array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float16)
>>> a_d.astype('float32')
gpuarray.array([[ 15360.,  15360.],
       [ 15360.,  15360.]], dtype=float32)
```

**Comment by abergeron** [comment]
Yes, that is normal, float16 is not correctly supported everywhere in libgpuarray operations.

We have to add some wrappers to make it work.

**Comment by nouiz** [comment]
Until it is done, we should raise an not implemented error. We should never
return wrong value.

**Comment by nouiz** [comment]
Now we raise an error, so the rest of this PR is to add support for this.

**Comment by nouiz** [comment]
I'm closing and make a new issue with a better title to the current need:

https://github.com/Theano/libgpuarray/issues/316
