### ISSUE TITLE
Win 10 installation

### ISSUE THREAD

**Issue by masakinakada** [Theano/libgpuarray#317]
Hi,

I am getting following error after cmake, when I am building using visual studio 2013

Can you please help me to fix the build error?
2>C:\Libs\libgpuarray\src\cache.h(12): error C2143: syntax error : missing ')' before '*'
2>C:\Libs\libgpuarray\src\cache.h(12): error C2143: syntax error : missing '{' before '*'
2>C:\Libs\libgpuarray\src\cache.h(12): error C2059: syntax error : ')'
2>C:\Libs\libgpuarray\src\cache.h(12): warning C4431: missing type specifier - int assumed. Note: C no longer supports default-int
2>C:\Libs\libgpuarray\src\cache.h(12): warning C4218: nonstandard extension used : must specify at least a storage class or a type
2>C:\Libs\libgpuarray\src\cache.h(66): error C2061: syntax error : identifier 'cache_hash_fn'
2>C:\Libs\libgpuarray\src\cache.h(70): error C2059: syntax error : '}'
2>C:\Libs\libgpuarray\src\cache.h(73): error C2146: syntax error : missing ')' before identifier 'khash'
2>C:\Libs\libgpuarray\src\cache.h(73): error C2081: 'cache_hash_fn' : name in formal parameter list illegal
2>C:\Libs\libgpuarray\src\cache.h(73): error C2061: syntax error : identifier 'khash'
2>C:\Libs\libgpuarray\src\cache.h(73): error C2059: syntax error : ';'
2>C:\Libs\libgpuarray\src\cache.h(73): error C2059: syntax error : ','
2>C:\Libs\libgpuarray\src\cache.h(74): error C2059: syntax error : ')'
2>C:\Libs\libgpuarray\src\cache.h(78): error C2146: syntax error : missing ')' before identifier 'khash'
2>C:\Libs\libgpuarray\src\cache.h(78): error C2081: 'cache_hash_fn' : name in formal parameter list illegal
2>C:\Libs\libgpuarray\src\cache.h(78): error C2061: syntax error : identifier 'khash'
2>C:\Libs\libgpuarray\src\cache.h(78): error C2059: syntax error : ';'
2>C:\Libs\libgpuarray\src\cache.h(78): error C2059: syntax error : ','
2>C:\Libs\libgpuarray\src\cache.h(79): error C2059: syntax error : ')'
2>C:\Libs\libgpuarray\src\cache.h(83): error C2037: left of 'add' specifies undefined struct/union '_cache'
2>C:\Libs\libgpuarray\src\cache.h(83): warning C4033: 'cache_add' must return a value
2>C:\Libs\libgpuarray\src\cache.h(87): error C2037: left of 'del' specifies undefined struct/union '_cache'
2>C:\Libs\libgpuarray\src\cache.h(87): warning C4033: 'cache_del' must return a value
2>C:\Libs\libgpuarray\src\cache.h(91): error C2037: left of 'get' specifies undefined struct/union '_cache'
2>C:\Libs\libgpuarray\src\cache.h(91): warning C4033: 'cache_get' must return a value
2>C:\Libs\libgpuarray\src\cache.h(95): error C2037: left of 'destroy' specifies undefined struct/union '_cache

**Comment by abergeron** [comment]
This looks line VS2013 doesn't like typedefs of function pointers.

This is accepted by VS2008 so I'm surprised.  If it works ojn 2010 and 2015, I fear the solution will have to be to use a different compiler.

**Comment by masakinakada** [comment]
@abergeron I did not know that! Thank you very much! I will try with other version of VS then!

**Comment by jrao1** [comment]
Actually I think this is because VS2013 doesn't recognize types like uint32_t

**Comment by abergeron** [comment]
Those are provided on windows via gpuarray/config.h.  So this part should be ok.

**Comment by jrao1** [comment]
@abergeron Right, but there seems to be a problem with gpuarray/config.h, on line 30 it checks _MSC_VER and only include gpuarray/wincompat/stdint.h if _MSC_VER is less than 1600, but it didn't do anything then _MSC_VER is bigger than 1600, I think it is missing an "else" which includes <stdint.h>?

**Comment by abergeron** [comment]
That is possible, yes.  Can you add it and see it it fixes your problem?  If it does I would welcome a PR.

**Comment by masakinakada** [comment]
Thank you very much guys!!
