### ISSUE TITLE
For pygpu: python setup.py build on macOS sierra file not found error 

### ISSUE THREAD

**Issue by abitofalchemy** [Theano/libgpuarray#319]
After installing the Cython module, I executed the following line:
`python setup.py build` and get the following error

`pygpu/gpuarray.c`:466:10: fatal error: `gpuarray/config.h` file not found
`#include "gpuarray/config.h"`
`         ^`

To get around this I made the following modification to `setup.py` 
 >current_dir = os.path.abspath(os.path.dirname(__file__))
 >include_dirs += [os.path.join(current_dir, 'src')]

The above was added before line: 
`if sys.platform == 'win32' and not os.getenv('CONDA_BUILD'):`

I am going down the wrong rat-hole?

**Comment by abergeron** [comment]
The python module is intended to be built after the main library has been installed.  Do that first and it should work.

**Comment by baharian** [comment]
i got the same error as @abitofalchemy. i have already successfully installed `libgpuarray` according to the instructions [here](http://deeplearning.net/software/libgpuarray/installation.html).

I noticed that `gpuarray/config.h` is installed in `/usr/local/include/` and the libraries `libgpuarray.dylib` and `libgpuarray-static.a` are installed in `/usr/local/lib/`. so i tried the following command `python setup.py build_ext -L /usr/local/lib -I /usr/local/include` (again, following the instructions in the link i mentioned above) which seemed to resolve the issue (barring a couple of warning about deprecated NumPy APIs). after this, i ran `python setup.py install` which installed pygpu 0.6.0rc1.

**Comment by abergeron** [comment]
Maybe the default install directories are not in the compiler's default path.  I will update the docs in mac specific section to point this out.

**Comment by baharian** [comment]
I am using OS X El Capitan, by the way.

**Comment by abergeron** [comment]
This add a blurb with your solution to the docs: https://github.com/Theano/libgpuarray/pull/321

**Comment by pazzjurist** [comment]
Thanks - same thing happened to me with Ubuntu 16.04. the `python setup.py build_ext -L /usr/local/lib -I /usr/local/include` fixed the config.h not found fatal error.

**Comment by abergeron** [comment]
On linux the proper solution is to run `sudo ldconfig` to rebuild the shared library cache (or reboot the system, which will have the same effect) as noted in the documentation.
