### ISSUE TITLE
Win10 Installation with python setup.py for libgpuarray

### ISSUE THREAD

**Issue by masakinakada** [Theano/libgpuarray#329]
Dear Community, I have a following problem and run the setup script for libgpuarray 
Could anyone help me to fix this? 
Thank you very much in advance.

I run this command and am getting following error. 
>python setup.py build_ext -L "C:/Program Files (x86)/libgpuarray/lib" -I "C:/Program Files (x86)/libgpuarray/include"

...................
creating build\lib.win-amd64-2.7\pygpu
C:\TDM-GCC-64\bin\gcc.exe -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o build\temp.win-amd64-2.7\Release\pygpu\gpuarray.def -LC:\Libs\libgpuarray-master\lib\Release "-LC:/Program Files (x86)/libgpuarray/lib" -LC:\Libs\Anaconda2\libs -LC:\Libs\Anaconda2\PCbuild\amd64 -LC:\Libs\Anaconda2\PC\VS9.0\amd64 -lgpuarray -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\pygpu\gpuarray.pyd
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray-master\lib\Release/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray-master\lib\Release/gpuarray.dll when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray-master\lib\Release/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray-master\lib\Release/gpuarray.dll when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray-master\lib\Release\gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib\gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgpuarray
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\TDM-GCC-64\\bin\\gcc.exe' failed with exit status 1

**Comment by nouiz** [comment]
Update libgpuarray. We did a fix that should help with this.

Le jeu. 12 janv. 2017 19:15, masakinakada <notifications@github.com> a
écrit :

**Comment by masakinakada** [comment]
Hi @nouiz Thank you very much for the fix. 

However, Still getting this error 
pygpu/gpuarray.c:21333:12: warning: '__pyx_pw_5pygpu_8gpuarray_8GpuArray_17__bool__' defined but not used [-Wunused-function]
 static int __pyx_pw_5pygpu_8gpuarray_8GpuArray_17__bool__(PyObject *__pyx_v_self) {
            ^
writing build\temp.win-amd64-2.7\Release\pygpu\gpuarray.def
C:\TDM-GCC-64\bin\gcc.exe -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\pygpu\gpuarray.o build\temp.win-amd64-2.7\Release\pygpu\gpuarray.def -LC:\Libs\libgpuarray\lib\Release "-LC:/Program Files (x86)/libgpuarray/lib" -LC:\Libs\Anaconda2\libs -LC:\Libs\Anaconda2\PCbuild\amd64 -LC:\Libs\Anaconda2\PC\VS9.0\amd64 -lgpuarray -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\pygpu\gpuarray.pyd
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release/gpuarray.dll when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release/gpuarray.dll when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Libs\libgpuarray\lib\Release\gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib/gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/Program Files (x86)/libgpuarray/lib\gpuarray.lib when searching for -lgpuarray
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgpuarray
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\TDM-GCC-64\\bin\\gcc.exe' failed with exit status 1

Please help me if you know what is wrong here...
Masaki

**Comment by abergeron** [comment]
This part:
```
skipping incompatible C:/Program Files (x86)/libgpuarray/lib/gpuarray.lib when searching for -lgpuarray
```
Should hint you that the built version of libgpuarray is not built in the same way as you python.  It might be a 32 bits vs 64 bits issue.

**Comment by masakinakada** [comment]
Thank you @abergeron !
It solved one of the problems!

**Comment by abergeron** [comment]
Also, I just noticed that you are using gcc to compile the python module on windows.  This is not supported and you should use the same MSVC that was used to compile python (and the library).

**Comment by abergeron** [comment]
We only support conda packages on windows.
