### ISSUE TITLE
Point to Point communication

### ISSUE THREAD

**Issue by hma02** [Theano/libgpuarray#330]
Hi @abergeron ,

Beside collective communication, I wonder if it is possible to do point to point communication right now based on gpucomm.

The way I'm using right now is a bit hacky and wasting resources. First, I create a gpucomm between the sender and receiver. Then I do a Bcast between the sender and receiver on the array.

Is there a better way of doing this?

Thanks

**Comment by nouiz** [comment]
I didn't try, but I think a normal gpu transfer between the 2 gpus can be
done by GpuToGpu inside Theano. The c code call pygpu_transfer. Does that
fit your need?

**Comment by hma02** [comment]
Hi @nouiz ,

Thanks for pointing `pygpu_transfer` out. I searched around and found [this line](https://github.com/Theano/libgpuarray/blob/fde02d272470fa6a3db4051d953291bc73c2bbd9/src/gpuarray_buffer.c#L121) in libgpuarray. 

Idealy, I need to do transfer between GPUs in a P2P way instead of passing host like after [this line](https://github.com/Theano/libgpuarray/blob/fde02d272470fa6a3db4051d953291bc73c2bbd9/src/gpuarray_buffer.c#L126). If this functions can be wrapped into a python function, that will very helpful to what I'm doing. 

I was also thinking of the other way, using IPC handle to pass the address and shape of array1 to the other process to be read in that process like what we did last summer for parallel loading. But just seems a lot of coding overhead.

**Comment by nouiz** [comment]
I let @abergeron reply for more detail.

I'm pretty sure that is pygpu_transfer isn't in the python interface
already, it is easy to add.

I forgot the detail to do IPC handle to have the same buffer visible
between 2 process.

**Comment by abergeron** [comment]
pygpu_transfer won't really help you since it only works within a single process.

I don't see why you think that the way you're using gpucomm is hacky.  This is the way it's meant to be used.  To avoid overhead you should reuse the channel whenever you need it, but otherwise it seems fine to me.

**Comment by hma02** [comment]
Thanks @abergeron,

Yeah, I was doing the transter across processes. I will still use Bcast then.

**Comment by nouiz** [comment]
I don't get why doing a broadcast between process is the best way to do
this. Why after having transfered the ptr, you can't use normal GPU to GPU
transfer?

**Comment by abergeron** [comment]
Because transferring the pointer is a pain in the ass and somewhat fragile.  Using NCCL broadcast with a group of two is probably just as efficient and easier to code.

**Comment by nouiz** [comment]
Okay, you use broadcast instead of ptr transfer. I was thinking he was
doing both!
