### ISSUE TITLE
cannot execute make install on v.0.6.0

### ISSUE THREAD

**Issue by nvarini** [Theano/libgpuarray#331]
Hi, I am trying to install https://github.com/Theano/libgpuarray/releases/tag/v0.6.0-rc1.
When I do make install it happen.
CMake Error at src/cmake_install.cmake:66 (file):
  file INSTALL cannot find
  "/home/nvarini/libgpuarray-0.6.0-rc1/lib/libgpuarray.so.0.0".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)
  

make: *** [install] Error 1

Thanks,

Nicola

**Comment by abergeron** [comment]
I never had this not working before.  Did you run `make` first?  Did it complete without errors?  Is the file it's looking for actually there?

**Comment by nvarini** [comment]
Sorry, I did rebuild from scratch and now it worked.
Thanks.

**Comment by Kairobo** [comment]
Have you tried "sudo make install"?
