### ISSUE TITLE
Literals seem to be broken in GpuElemwise (at least)

### ISSUE THREAD

**Issue by kohr-h** [Theano/libgpuarray#339]
I encountered a very weird error. When creating an elementwise kernel using `pygpu.elemwise.GpuElemwise`, all float literals seem to be treated as integers. Check out [this code](https://gist.github.com/kohr-h/4c125230c375fc6f843e40c825af026d) and if you can reproduce the error. I'm using CUDA 8.

Here's an example:
```python
import pygpu
ctx = pygpu.init('cuda')
pygpu.set_default_context(ctx)
x = pygpu.gpuarray.array([0.9, 1.05, 1.3, 1.8, 1.95, 2.1], dtype='float64')
out = x._empty_like_me()
x_arg = pygpu._elemwise.arg('x', x.dtype, read=True)
out_arg = pygpu._elemwise.arg('out', out.dtype, write=True)
args = [out_arg, x_arg]
expr = 'out = x + 2.5'
kernel = pygpu.elemwise.GpuElemwise(x.context, expr, args)
kernel(out, x)
print('x:', x)
print('out:', out)
```
The output is:
```
x: [ 0.9   1.05  1.3   1.8   1.95  2.1 ]
out: [ 2.9   3.05  3.3   3.8   3.95  4.1 ]
```
which is `x + 2`, not `x + 2.5`.

**Comment by kohr-h** [comment]
Update: It only seems to happen in Spyder using the embedded IPython console. Very weird. When I run it in the standard Python console, everything is correct. Also when I run it from the command line.

**Comment by kohr-h** [comment]
Nah, so the error clearly lies elsewhere, closing this.

**Comment by nouiz** [comment]
I tried here in python, ipython and spyder and it work in all cases.

It is with cuda 8.

Could it be that you have spyder use a different libgpuarray/pygpu/theano
version? I think it use a different default for python package path.

**Comment by kohr-h** [comment]
> Could it be that you have spyder use a different libgpuarray/pygpu/theano
> version? I think it use a different default for python package path.

No, I actually rebuilt the library using conda and updated it in my working environment. I also checked `pygpu.__path__` and it points to the correct location.

One very weird way in which things could be messed up by Spyder is the graphical backend that the IPython console tries to manage (which it doesn't if I use IPython on the console, where things work). I have a single graphics card in my computer, so if IPython manages to mess around with GPU contexts in some way, it could possibly affect later GPU computations.
But that's only the best guess I currently have.

**Comment by kohr-h** [comment]
So in fact, the erroneous behavior only occurs in the combination of KDE and the QT5 backend for matplotlib. When I choose QT4 or inline, or when I switch to XFCE, for example, no problem any more. Spooky.

**Comment by nouiz** [comment]
@abergeron, do you have an idea?

**Comment by abergeron** [comment]
My only one is that string get somehow corrupted in between python and libgpuarray.
