### ISSUE TITLE
python 3 compat for pygpu

### ISSUE THREAD

**Issue by abergeron** [Theano/libgpuarray#35]
We should test pygpu on python 3 and fix the problems.

**Comment by jmwoloso** [comment]
+1

**Comment by nouiz** [comment]
Do you want to help us on that? We are pretty busy and this isn't high on
our priority list.

On Mon, Nov 9, 2015 at 2:31 AM, Jason Wolosonovich <notifications@github.com

**Comment by jmwoloso** [comment]
Sure! Though, as a fair warning, I've never ported an existing code base, but I'm all for trying it.

On 11/13/2015 08:44 AM, Frédéric Bastien wrote:
Do you want to help us on that? We are pretty busy and this isn't high on
our priority list.

On Mon, Nov 9, 2015 at 2:31 AM, Jason Wolosonovich <notifications@github.com<mailto:notifications@github.com>
