### ISSUE TITLE
After upgrading to 0.9.0b1 training never starts

### ISSUE THREAD

**Issue by subzerofun** [Theano/libgpuarray#358]
OS: MacOS Sierra 10.12
GPU: GTX 780
CUDA: 8.0, Cudnn 5.1

Installed the newest theano and libgpuarray versions from source, compiled libgpuarray without errors.

Was trying to run this project:
**Keras WaveNet implementation**
https://github.com/basveeling/wavenet

But after showing the model in the terminal output the training never starts and just quits after 2-5min doing nothing. I'm sure that the code is OK and something is wrong on my side.

I have the exact same problem with another project, the training simply never starts...
https://github.com/MattVitelli/GRUV
**As soon as i switch back to Theano 0.8.2 this project is working again.** 

But a lot of people are building their new projects on Theano >0.9 and unfortunately i can’t run them with Theano 0.8.2.

I checked the free memory on my card, it was around 3-4 GB (from 6GB) – this should be enough. And if that was the problem i would see a memory allocation error somewhere.

The first example from http://deeplearning.net/software/theano/tutorial/using_gpu.html
only works with the flags `THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32`
when i try to change `device` to `cuda` or `cuda0` the cpu is used.

Example nr.2 and 3 works with `device=cuda` – the gpu is being used.

I then tried `theano.test()` and this is the output:
```
Python 2.7.12 (default, Oct 11 2016, 05:20:59)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Using cuDNN version 5105 on context None
Mapped name None to device cuda: GeForce GTX 780 (0000:01:00.0)
>>> theano.test()
Theano version 0.9.0beta1.dev-8757c2dc05a86ba0e8ff0febb0cd415183da434a
theano is installed in /usr/local/lib/python2.7/site-packages/theano
NumPy version 1.12.0
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
Python version 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
nose version 1.3.7
/usr/local/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py:10: UserWarning: theano.sandbox.gpuarray has been moved to theano.gpuarray. Please update your code and pickles. If the warning persists, clear theano's cache ('$theano/bin/theano-cache clear').
  warnings.warn(message)
...................................S.........................................S........................../usr/local/lib/python2.7/site-packages/theano/compile/nanguardmode.py:154: RuntimeWarning: All-NaN slice encountered
  return np.isinf(np.nanmax(arr)) or np.isinf(np.nanmin(arr))
/usr/local/lib/python2.7/site-packages/theano/compile/nanguardmode.py:154: RuntimeWarning: All-NaN axis encountered
  return np.isinf(np.nanmax(arr)) or np.isinf(np.nanmin(arr))
..............................................EE.........SS.............0.0581646137166
0.0581646137166
0.0581646137166
0.0581646137166
........................................................................................................................................................../usr/local/lib/python2.7/site-packages/theano/gof/vm.py:870: UserWarning: LoopGC does not support partial evaluation, using Stack VM.
  'LoopGC does not support partial evaluation, '
...F...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...............S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..................Segmentation fault: 11
```

So the tests don't run till the end, the python process abruptly crashes with `Segmentation fault: 11`

I have tried to uninstall theano, libgpuarray and keras, cleaned all older versions i could find (also the .theano folder in my home directory). Then reinstalled everything from source, but the problem still persists...

I hope someone could help me to find out what’s wrong with my installation!

**Comment by nouiz** [comment]
I suppose it is fixed, but we just merged a segfault fix for the new
back-end. So if you see this, make sure to update Theano to the dev
version. The fix will be included in Theano 0.9rc1

**Comment by subzerofun** [comment]
Oh thanks for the info, i just realized that i posted this on the wrong site (libgpuarray) – i wrote a new issue on Theano/theano.

Tried a second test and got another error: https://github.com/Theano/Theano/issues/5560

Will try to update theano and rerun the tests. Do i need to reinstall libgpuarry as well?

**Comment by nouiz** [comment]
I think you don't need to reinstall libgpuarray.
