### ISSUE TITLE
Failed installing libgpuarray in virtualenv

### ISSUE THREAD

**Issue by xingniu** [Theano/libgpuarray#362]
Theano-0.9.0rc1 with the cuda backend works well for me. I tried to install the gpuarray backend as follows:

`git clone https://github.com/Theano/libgpuarray.git`
`cd libgpuarray`
`mkdir Build`
`cd Build`
`cmake .. -DCMAKE_INSTALL_PREFIX=/path/to/my/virtualenv -DCMAKE_BUILD_TYPE=Release`
`make`
`make install`
`cd ..`
`export CPATH=$CPATH:/path/to/my/virtualenv/include`
`export LIBRARY_PATH=$LIBRARY_PATH:/path/to/my/virtualenv/lib`
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/my/virtualenv/lib`
`python setup.py build
`python setup.py install`
`cd`

After the installation, I tested as
`DEVICE=cuda python -c "import pygpu;pygpu.test()"`
and then got
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/my/virtualenv/lib/python2.7/site-packages/pygpu-0.6.1-py2.7-linux-x86_64.egg/pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
ImportError: libgpuarray.so.2: cannot open shared object file: No such file or directory

Does anyone have any suggestion? Thanks!

**Comment by xingniu** [comment]
Never mind, I tried again using a clean virtualenv and it worked.

**Comment by alyato** [comment]
@xingniu  I don't use the virtualenv to install. But it also show me the same question. 
Do you give me some advice? Thanks.

**Comment by abergeron** [comment]
You need nose installed for the tests.

Also, please don't post comments on closed issues unless you have reason to believe that the problem is not actually fixed and it is a bug in pygpu/libgpuarray
