### ISSUE TITLE
Document blacklisted NVIDIA driver versions?

### ISSUE THREAD

**Issue by rajb245** [Theano/libgpuarray#363]
`DEVICE=cuda0 python -c "import pygpu;pygpu.test()`

I get 

> "ERROR: refusing to load cuda driver library because the version is blacklisted.  Versions 373.06 and below are known to be ok."

I see this is version check from here: https://github.com/Theano/libgpuarray/blob/4da85f6cef59f6e8641e3a906623ee5fb1eecd62/src/loaders/libcuda.c#L73

As of today, the latest version NVIDIA is shipping in the [x86_64 Ubuntu 16.04 repo](http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64) is 375.26, so the python tests fail. However, forcing things with 
`GPUARRAY_FORCE_CUDA_DRIVER_LOAD=1 DEVICE=cuda0 python -c "import pygpu;pygpu.test()" `
works just fine.

I suggest two steps to resolve this:

1. Test libgpuarray thoroughly on NVIDIA driver 375.26 and then bump the blacklist check up to this version number
2. Document the version that your driver has to be older than in the [install documentation](http://deeplearning.net/software/libgpuarray/installation.html). This could be automated by making the version threshold a "#define" macro and getting the Sphinx documentation to pick up on that version number automatically and inserting the value into the install instructions, saying "your NVIDIA driver must be older than $(CUDA_DRIVER_VERSION_CUTOFF)". What I mean for libcuda.c is:
```
#define CUDA_DRIVER_VERSION_CUTOFF 375.26
//... jump ahead
v = ga_lib_version(lib, cuInit);
if (v > CUDA_DRIVER_VERSION_CUTOFF)
{
//... print the error message
}
```
I'm no sphinx expert but a [stackoverflow post](http://stackoverflow.com/questions/24080491/print-the-variable-value-in-a-sphinx-document) makes me think it is possible to output the values of variables and/or macros wherever you want in Sphinx documentation.

**Comment by abergeron** [comment]
The 375.26 driver has the bug we are watching for with the blacklist (which is a reordering of memory load when using warp synchronous programming).  We did test.  It just doesn't show up in the testsuite for pygpu.

**Comment by abergeron** [comment]
However, we've been advised by NVIDIA that warp synchronous programming is no longer supported and will work on avoiding instances of it.  Then we will probably get rid of the blacklist.
