### ISSUE TITLE
make test failures on "collectives"

### ISSUE THREAD

**Issue by rajb245** [Theano/libgpuarray#364]
**Summary**
====================
I get failures on the two "collectives" tests (test_buffer_collectives and test_collectives). The [verbose ctest output](https://github.com/Theano/libgpuarray/files/804576/libgpuarray_ctest_errors.txt) for the following command is attached.

`GPUARRAY_FORCE_CUDA_DRIVER_LOAD=1 DEVICE=cuda0 ctest -V -R collectives`

Basically looks like a bunch of "GA_NO_ERROR" errors are returned, but that's not really an error it seems? If you need more info from me, please let me know.

**System Info**
====================
NVIDIA Titan X Pascal
NVIDIA Driver 375.26
Xubuntu 16.04
x86_64 arch
OpenMPI, cmake, python, check, python-mako, and python-nose installed from Ubuntu repos
```
user@system:~/libgpuarray/build$ mpiexec --version
mpiexec (OpenRTE) 1.10.2
```
cython installed from pip (this is because Ubuntu ships 0.23 in the repos, while 0.25 or later is required)
```
user@system:~/libgpuarray/build$ pip show cython
---
Metadata-Version: 2.0
Name: Cython
Version: 0.25.2
...
```

**Build Steps**
====================
```
git clone https://github.com/Theano/libgpuarray.git
cd libgpuarray
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j8
sudo make install
sudo ldconfig
#install the pygpu piece
cd ..
python setup.py build
sudo python setup.py install
```

**Comment by abergeron** [comment]
A library fails to load (as indicated by the error code 18).  It's probably NCCL.

**Comment by rajb245** [comment]
Project seems dead, closing
