### ISSUE TITLE
"changes address space of pointer" CL compile error

### ISSUE THREAD

**Issue by marcoesposito1988** [Theano/libgpuarray#368]
Hi guys,

I am trying to get Theano v0.9.0rc2 with libgpuarray v0.6.1 running on my Radeon 7850 card.

Only two tests from pygpu.test() fail, regarding float16 (I guess the GPU architecture doesn't support them). However, trying any keras example, I get the following error:

```
OpenCL Warning : clBuildProgram failed: could not build program for 0x1021c00 (AMD Radeon HD Pitcairn PRO Prototype Compute Engine) (err:-2)

[CL_BUILD_ERROR] : OpenCL Build Error : Compiler build log:
<program source>:101:16: error: initializing 'float *' with an expression of type '__global float *' changes address space of pointer

DTYPE_i0 * data_col_ptr = data_col;
```

My very limited understanding is that such code is not legal for OpenCL 1 (the card supports OpenCL1.2), but should run under OpenCL2. May it be that the code is generated for the wrong target version? 

Thanks for your great work, I hope I will be able to use this workstation soon! :)

**Comment by nouiz** [comment]
libgpuarray should work with OpenCL, but it miss many optimizations. But a bigger problem is that Theano didn't port to OpenCL all its code for now. So even if this problem get fixed, you will hit other problems shortly.

Are you ready to help us? We don't have time to work on the OpenCL support, but we could guide you.

**Comment by marcoesposito1988** [comment]
Well, I don't know if I will manage, but I can try (I always wanted to try some GPU programming). Is there any list of tasks for beginners somewhere? This could be of general interest.

**Comment by nouiz** [comment]
I think the first step would be to fix the error you have:)

Can you check the full error message and go in the test in the error line.
There you can probably see which operation try to compile and fail.

There isn't a real list of problems to fix. When pygpu pass, it would be to
make Theano tests pass. Slowly, more stuff have been ported to opencl.
There is this issue that list a few problems reported by users:
https://github.com/Theano/Theano/issues/2936

**Comment by nouiz** [comment]
There is also this old list of ops. I think the opencl status isn't up to
date, but what is listed as working should still work:

https://github.com/Theano/Theano/issues/1471

**Comment by marcoesposito1988** [comment]
These look like excellent starting points, thanks!

By the way, I managed to find the respective issue for Theano: Theano/Theano#5504

So I will close this one. I hope you will hear from me, maybe in a pull request!
