### ISSUE TITLE
32bit TX1 have no nvrtc :(

### ISSUE THREAD

**Issue by guoxuesong** [Theano/libgpuarray#369]
> Use nvrtc for kernel compilation when available

Could you please find back the code for that nvrtc not available ?

**Comment by abergeron** [comment]
The 32-bit environment is deprecated and no longer supported by NVIDIA, if you update your TX1 to the 24.2.1 image with JetPack 2.3.1, you will get a cuda that has nvrtc and can compile kernels dynamically with libgpuarray.

If you absolutely need support for no nvrtc, then I advise you to use an older version of libgpuarray from before the nvcc code was removed.

**Comment by nouiz** [comment]
@abergeron, is that version too old? Maybe it would be better if they use
Theano to use the old Theano gpu back-end? What do you think about those 2
options?

**Comment by nouiz** [comment]
This was removed by this commit:

commit 9776c9d37b399b834bb38d071bdb2157cbfbb1d7
Author: Arnaud Bergeron <abergeron@gmail.com>
Date:   Wed Nov 9 14:24:59 2016 -0500

Just for your information in case it help you.

**Comment by abergeron** [comment]
The 32-bit version is 23.1 and 24.1 is both 32 and 64 bits. The current version is 24.2 (soon to be bumped up).

The problem with the 32-bit version and 24.1 is that they don't have nvrtc. (even though 24.1 claims to be cuda 7.0).

Also, this the libgpuarray issues so I don't propose Theano solutions, but sure if you are using Theano, then the old backend is also an alternative.

**Comment by guoxuesong** [comment]
I have upgraded my device to 64bit
