### ISSUE TITLE
Build failing on OS X 10.9

### ISSUE THREAD

**Issue by cdg720** [Theano/libgpuarray#37]
Hi,

I need some help to install libgpuarray on my mac. When I type "cmake .. -DCMAKE_BUILD_TYPE=Release", I get the following: 
-- The C compiler identification is AppleClang 6.0.0.6000056
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found CUDA: /usr/local/cuda (found version "6.5") 
-- Found OpenCL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenCL.framework  
-- Looking for strlcat
-- Looking for strlcat - found
-- Looking for mkstemp
-- Looking for mkstemp - found
Cuda 6.0+ does not come in universal flavor anymore so we disable the universal build.
-- Could NOT find clBLAS (missing:  CLBLAS_LIBRARIES CLBLAS_INCLUDE_DIRS) 
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.28") 
-- checking for one of the modules 'check'
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dokookchoe/research/stuff/libgpuarray/Build

I think it has trouble finding "check". When I type "make", I get error messages:
Linking C executable check_buffer
ld: library not found for -lcheck
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tests/check_buffer] Error 1
make[1]: *** [tests/CMakeFiles/check_buffer.dir/all] Error 2

For some reasons, it couldn't find "check" and failed to link it when "make" was invoked (I think). I installed "check" using "brew install check". "check" is installed in the following directories:
/usr/local/Cellar/check
/usr/local/Cellar/check/0.9.14/share/doc/check
/usr/local/Library/LinkedKegs/check
/usr/local/opt/check
/usr/local/share/doc/check

Can anyone help me out?

Thanks,
DK

**Comment by cdg720** [comment]
Setting PATH to /usr/local/Cellar/check/0.9.14/include/ and LIBRARY_PATH to /usr/local/Cellar/check/0.9.14/lib/ solved the problem.

**Comment by aakansh9** [comment]
I am encountering the following problem: 

log of cmake .. -DCMAKE_BUILD_TYPE=Release shows:

```
-- checking for one of the modules 'check'
Tests disabled because Check was not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/gupta/libgpuarray/Build
```

How to change the PATH and LIBRARY_PATH for cmake to find check? (I also installed check using brew)

**Comment by loretoparisi** [comment]
I get this error. Environment: docker with `Ubuntu16.0.4LTS`

```
# libgpuarray
# @see http://deeplearning.net/software/libgpuarray/installation.html
RUN \
    git clone https://github.com/Theano/libgpuarray.git && \
    cd libgpuarray && \
    mkdir Build && \
    cd Build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make && \
    sudo make install && \
    cd .. && \    
    python setup.py build && \
    python setup.py install && \
    sudo ldconfig
```
