### ISSUE TITLE
test_elemwise.test_infinity failed

### ISSUE THREAD

**Issue by astooke** [Theano/libgpuarray#370]
Hi,
I just pulled the current libgpuarray git, installed, and tested with the following result:

```
======================================================================
ERROR: pygpu.tests.test_elemwise.test_infinity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda2/envs/rlmj/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/anaconda2/envs/rlmj/lib/python3.5/site-packages/pygpu-0.6.1-py3.5-linux-x86_64.egg/pygpu/tests/test_elemwise.py", line 324, in test_infinity
    preamble=preamble)
  File "pygpu/_elemwise.pyx", line 137, in pygpu._elemwise.GpuElemwise.__cinit__ (pygpu/_elemwise.c:3090)
pygpu.gpuarray.GpuArrayException: Could not initialize C GpuElemwise instance

----------------------------------------------------------------------
Ran 7000 tests in 166.971s

FAILED (errors=1)
```

Probably just some sort of typo in the test code?  Let me know if you want system details.

**Comment by abergeron** [comment]
That test passes on my machine both in cuda and opencl mode.

Please give me the system details (backend used, backend toolkit and version).

**Comment by jc-Rosichini** [comment]
Encountered the same issue, see https://github.com/Theano/Theano/issues/5659 part II.

**Comment by abergeron** [comment]
Someone else had the problem and mentioned that he was running on Windows 10.  This may be relevant as I never had this problem on Linux.  @astooke are you on windows too?

**Comment by astooke** [comment]
Hey, sorry this took me a few days.... I'm on Ubuntu 16.04, Python 3.5.2.  When I call `git describe --tags` in my libgpuarray clone it returns `v0.6.1-4-g56b2df4`.  I'll update now and see if it still happens.

**Comment by astooke** [comment]
Yes it still happens with v0.6.2.  But only on one of two systems I'm running.  The one that fails is a GTX 1080, NumPy version 1.11.3.  The one that passes is a Tesla P100, NumPy version 1.11.2, Ubuntu 14.04.  Both CUDA-8.0, same Python version.  (I never had v0.6.1 on the passing system.)

**Comment by abergeron** [comment]
Two things.  Can you check what are the driver version on those two machines?

Also can you try with this branch: https://github.com/abergeron/libgpuarray/tree/fix_inf_p

**Comment by astooke** [comment]
NVIDIA driver on the failing machine: 370.28, on the passing machine: 375.26.

OK I tried a fresh install by that branch, and the error remains the same.  

Btw I'm still installing using [theses instructions](http://deeplearning.net/software/libgpuarray/installation.html).  I wipe the old /include and /lib files before re-installing (to external directory), but in case there is a chance I am linking to some old version, is there a conda install comand that makes sure to do everything right and links correctly?

**Comment by abergeron** [comment]
I'll try to get driver 370.28 installed to see if that is the cause of the problem.

Also, the "fix" is in python code only so there shouldn't be any problems with leftovers.

**Comment by jc-Rosichini** [comment]
fyi. Still getting the same problem with the latest pygpu/libgpuarray and Nvidia driver 378.78 on windows 10


> E:\>python -c "import pygpu;pygpu.test()"
> pygpu is installed in C:\Users\PCGP1\Anaconda3\lib\site-packages\pygpu-0.6.2-py3.5-win-amd64.egg\pygpu
> NumPy version 1.11.3
> NumPy relaxed strides checking option: False
> NumPy is installed in C:\Users\PCGP1\Anaconda3\lib\site-packages\numpy
> Python version 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
> nose version 1.3.7
> *** Testing for GeForce GTX 980M
> ..................................
> 
> 
> ERROR: pygpu.tests.test_elemwise.test_infinity
> 
> Traceback (most recent call last):
>   File "C:\Users\PCGP1\Anaconda3\lib\site-packages\nose\case.py", line 198, in runTest
>     self.test(*self.arg)
>   File "C:\Users\PCGP1\Anaconda3\lib\site-packages\pygpu-0.6.2-py3.5-win-amd64.egg\pygpu\tests\test_elemwise.py", line 324, in test_infinity
>     preamble=preamble)
>   File "pygpu\_elemwise.pyx", line 137, in pygpu._elemwise.GpuElemwise.__cinit__ (pygpu/_elemwise.c:3099)
> pygpu.gpuarray.GpuArrayException: Could not initialize C GpuElemwise instance
> 
> Ran 7000 tests in 432.786s

**Comment by lamblin** [comment]
Does it still happen with 0.6.5?

**Comment by jc-Rosichini** [comment]
As of today and with the current pygpu I don't see the issue anylonger on Windows 10.

(However note that the issue was manifesting on GeForce GTX 980M and not on other GPU board
I'm now using GP100 and GTX 1080 on desktop...)

So:
pygpu is installed in C:\Users\APYLOC\Anaconda3\lib\site-packages\pygpu-0.6.5-py3.6-win-amd64.egg\pygpu
NumPy version 1.11.3
NumPy relaxed strides checking option: False
NumPy is installed in C:\Users\APYLOC\Anaconda3\lib\site-packages\numpy
Python version 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
*** Testing for Quadro GP100
..........
Ran 7244 tests in 289.653s

OK

**Comment by lamblin** [comment]
Thanks for the update.
Please reopen or open a new one if the issue starts again.
