### ISSUE TITLE
Not able to use libgpuarray from Theano in Windows 7

### ISSUE THREAD

**Issue by ValeryAnisimovsky** [Theano/libgpuarray#378]
I was able to successfully build libgpuarray and install pygpu (which passes all tests in pygpu.test()), however I was not able to use it in Theano (by setting device to "cuda0" in .theanorc). 

There're at least two problems:
1) When I enable cuDNN I get error message "RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN". Even when I set include_path and library_path in [dnn] section of .theanorc, I still cannot use cuDNN with a bunch of error messages like "g++.exe: error: Files\NVIDIA: No such file or directory", so it seems that gcc is confused with whitespace-containing paths like "c:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include".
Note that when using old backend, cuDNN can be used without any problem.
2) Even if I disable cuDNN, I still cannot use the new backend, now the error message is "Exception: ('Compilation failed (return status=1): C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgpuarray", that is, gcc is not able to find gpuarray.lib. Putting gpuarray.lib built by MSVC to some path visible by gcc doesn't help, since it's in a format not suitable for gcc.

Both problems seem to result from usage of gcc instead of MSVC. Is there any way to configure Theano/libgpuarray so that MSVC is used?

My specs are: Windows 7 (x64), MSVC 2015, Python 2.7 (x64), Theano 0.9.0rc4, latest libgpuarray, CUDA 8.0, cuDNN 5.1.

**Comment by abergeron** [comment]
1. Use a more recent version of Theano, we've made fixes.
2. Are you sure you've built libgpuarray for 64-bit?  Did you use the same compiler as for python?  It should be this one: https://www.microsoft.com/en-us/download/details.aspx?id=44266

No, it's not possible to use MSVC to compile with Theano currently.  The support could be added, if you want to do the work.

Also, this is a Theano question, not a libgpuarray question, please use the Theano mailing list/issues in the future for similar issues.

**Comment by ValeryAnisimovsky** [comment]
Finally, I was able to make it work by producing gcc-compatible import libraries for gpuarray.dll and cudnn.dll. The only question remaining is the support for CNMeM: Theano with old backend used to get significant gains in speed when using it, while I cannot see any sign of memory pre-allocation when using gpuarray. Is there support for CNMeM in gpuarray?

**Comment by stevenxxiu** [comment]
@ValeryAnisimovsky How did you manage to get those? Theano for me constantly crashes on startup.

**Comment by nouiz** [comment]
@ValeryAnisimovsky, The new back-end use a different mechanism for the
memory. It don'T use that flag see:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

@stevenxxiu, make an issue with the full error you have. You can also
insatll the pre-build conda packages:

conda install -c rdonnely Theano

**Comment by ValeryAnisimovsky** [comment]
@nouiz, Ok, now I see, it's really useful.

@stevenxxiu, I used small Python script to produce import libs:

import os, sys, subprocess, itertools

if __name__ == '__main__':
    if len(sys.argv) >= 2:
        dll_name = sys.argv[1]
        res = subprocess.check_output(['dumpbin', '/exports', dll_name])
        res = map(lambda l: l.strip(), res.split('\n'))[19:]
        res = list(itertools.takewhile(lambda l: l, res))
        res = map(lambda l: l.split(' ')[-1], res)
        def_name = os.path.splitext(dll_name)[0] + '.def'
        with open(def_name, 'wt') as f:
            print>>f, 'LIBRARY', os.path.split(dll_name)[-1]
            print>>f, 'EXPORTS'
            for l in res:
                print>>f, l
        lib_name = os.path.splitext(dll_name)[0] + '.lib'
        os.system('dlltool -d %s -l %s' % (def_name, lib_name)) 

This script assumes that VC9's dumpbin.exe is available somewhere in the path (as well as tdm-gcc's dlltool.exe). The import libs are copied to Python's libs folder, then I added [gcc] section in .theanorc like this:
[gcc]
cxxflags = -I"c:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" -L"c:\Python\Python27\libs"

**Comment by nouiz** [comment]
We have not conda packages available. Can you use them? We don't have time to support many different configuration, so for now, this is the only one we officialy support on windows. Any help to have us support more configuration are welcome, we just don't have enough time to support all of them.

**Comment by stevenxxiu** [comment]
The conda package also works after extracting in vanilla python, but the
includes might need a manual install step.

**Comment by abergeron** [comment]
The only question remaining seems to be what to replace `lib.cnmem` with, and the answer is `gpuarray.preallocate`.

So I consider this closed.
