### ISSUE TITLE
Theano wont use CnMem when using libgpuarray

### ISSUE THREAD

**Issue by andrelopes1705** [Theano/libgpuarray#384]
**Theano is not using CNMEM when i use libgpuarray mode.**

.../LasagneModel$ THEANO_FLAGS=device=cuda2 python Main_Ensemble.py
Using cuDNN version 5110 on context None
Mapped name None to device cuda2: GeForce GTX TITAN X (0000:83:00.0)

**When i use nvidia-smi :** 
199MiB / 12206MiB
...
|    2     22154    C   python                                         195MiB

**On my .theanorc :** 

[global]
floatX = float32
allow_gc = True
optimizer_including=cudnn
mode = FAST_RUN
openmp = True

[cuda]
root= /home/andre/cuda

[nvcc]
fastmath=False

[lib]
cnmem=1

[dnn]
conv.algo_bwd_filter = deterministic
conv.algo_fwd = large
conv.algo_bwd_data  = deterministic
enabled=True

**Comment by lamblin** [comment]
This is normal.
The option that governs the preallocation for the new back-end is `gpuarray.preallocate`.
