### ISSUE TITLE
narrowing conversion error after cleaning theano cache

### ISSUE THREAD

**Issue by pixelou** [Theano/libgpuarray#403]
I have had issues with a model not training with libgpuarray recently.
After clearing the .theano cache directory, the model simply does not compile anymore when I use libgpuarray.

The error is related to some values bigger than 128 for a char array:
```mod.cpp:17:0: error: narrowing conversion of ‘168’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]```

The demo code and the error log are attached below. The only places where I manipulate integral variable with theano in this code is line 62 with the 'durations' variable and later for the labels in the fitting process but the script crashes before that point.

- Theano 0.9 : e79c4e4c83c5a4907ea7fddf073fd2d659df7486
- libgpuarray 0.6.4 : 211a73c414d40669fc4fcce018ae61dd37fd8f75 
- Lasagne : 45bb5689f0b2edb7114608e88305e8074d29bbe7
- pygpu : 211a73c414d40669fc4fcce018ae61dd37fd8f75
- cuda 8.0
- cudnn 5.1
- linux 4.10.8-1-ARCH(linux)

I think this bug belongs here but please tell me if I should open it on Theano instead.

[demo_script.py.txt](https://github.com/Theano/libgpuarray/files/914387/demo_script.py.txt)
[theano_compilation_error_i254cm0n.txt](https://github.com/Theano/libgpuarray/files/914388/theano_compilation_error_i254cm0n.txt)

**Comment by nouiz** [comment]
What is your version of g++?

Can you try that Theano flag?

gcc.cxxflags=-Wnarrowing

**Comment by nouiz** [comment]
I think the problem is that you use a more recent g++ version that we don't
support and is more strict. The flag should help. But I have a branch that
should fix that particular problem. Can you try it?

https://github.com/nouiz/Theano/tree/unsigned_char

**Comment by pixelou** [comment]
I can hardly understand why those errors can be ignored, but it seems to work correctly now, thank you.

**Comment by Ape** [comment]
I had the same error with Theano 0.9.0 and GCC 6.3.1. I fixed it by upgrading Theano to git master (b96a3223a).

**Comment by nouiz** [comment]
We can ignore them as the code is fine. In the past, compiler accept that
type of code and didn't warn about them. Ideally, we should fix all of
them. Not sure when we can work on that. If someone want to help have that
done faster, tell us!

**Comment by Rubikplayer** [comment]
Hi, sorry to open this again.

I have a similar issue. For my case, I have to run a code with theano 0.9. (I installed by `conda install theano=0.9`), so I cannot upgrade Theano to the latest version. 

Also, as @nouiz mentioned the flag should help. I tried the following two ways:
- run python script by `THEANO_FLAGS='gcc.cxxflags=-Wnarrowing' python ./main.py`
- add `gcc.cxxflags=-Wnarrowing` in `~/.theanorc`

Neither worked. Did I use this correctly?

More info:

- Ubuntu 16.04.2 LTS
- CUDA 8.0 / CuDNN 5.1
- gcc 5.4.0
- libgpuarray: 0.6.9-0
- pygpu: 0.6.9-py27_0
- theano: 0.9.0-py27ha72280b_3

If any suggestion, please let me know. Thanks!!

**Comment by Rubikplayer** [comment]
Issue solved by adding `gcc.cxxflags=-Wno-narrowing` in `~/.theanorc`
