### ISSUE TITLE
Add anaconda as installation option to documentation

### ISSUE THREAD

**Issue by Farbdose** [Theano/libgpuarray#418]
Could you add a note to the installation instructions, that anaconda is a valid alternative?

I just spent 2h getting make and cmake under windos 10 working to finally be able to compile libgpuarray...
Then found out that

    conda install pygpu

works too:

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        libgpuarray-0.6.4          |           vc14_0         242 KB
        requests-2.13.0            |           py35_0         823 KB
        mako-1.0.6                 |           py35_0         153 KB
        pygpu-0.6.4                |           py35_0         573 KB
        pyopenssl-16.2.0           |           py35_0          70 KB
        conda-4.3.16               |           py35_0         553 KB
        ------------------------------------------------------------
                                               Total:         2.4 MB

That would have been **much** faster...

**Comment by nouiz** [comment]
It is there in the dev version:

http://deeplearning.net/software/libgpuarray_versions/dev/installation.html

I just pushed it to the master/default doc. Should be up in a few minutes.

thanks
