### ISSUE TITLE
PyGPU Could Not Be Imported

### ISSUE THREAD

**Issue by thorlucas** [Theano/libgpuarray#421]
I'm getting the following error:

`ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)`

Yet according to conda I'm using pygpu 0.6.4.

I'm on macOS Sierra.

**Comment by lamblin** [comment]
You may have multiple versions of pygpu installed. You can check that by printing `pygpu.version.fullversion` and `pygpu.__path__`.
Remove all versions of pygpu and try to reinstall.

**Comment by kfmn** [comment]
I have the same error. But I have only version of pygpu within used anaconda environment:

**Comment by lamblin** [comment]
And if you remove it and try to import pygpu again?

**Comment by simonm3** [comment]
I have the same error. Tried uninstalling and reinstalling but made no difference.

**Comment by simonm3** [comment]
If I try to import it:

ImportError: /anaconda3/lib/python3.6/site-packages/pygpu/gpuarray.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PySlice_Unpack

**Comment by nouiz** [comment]
How did you install it?

Did you install it with:

conda install Theano pygpu

**Comment by simonm3** [comment]
yes but in 2 steps. pygpu and theano. does the order matter?

**Comment by nouiz** [comment]
I don't recall us testing on python 3.6, but I see there is the conda
packages.

Can you try the conda-forge packages just in case?

conda remote Theano pygpu
conda install -c conda-forge Theano pygpu

**Comment by GuillaumeLe** [comment]
The issue was closed but I have the same problem and reinstallations do not fix it.

Always the same error : 
ImportError: /anaconda3/lib/python3.6/site-packages/pygpu/gpuarray.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PySlice_Unpack

**Comment by nouiz** [comment]
How did you re-installed it?

**Comment by GuillaumeLe** [comment]
I used conda : `conda remove pygpu theano && conda install -c conda-forge pygpu theano`.

**Comment by nouiz** [comment]
Can you try just in case it make a difference?

conda remove pygpu theano && conda install pygpu theano.

**Comment by lamblin** [comment]
This ticket was closed because it is about a different problem altogether.

The new issue (`undefined symbol: PySlice_Unpack`) could be related to there being different versions of libpython on your system, the one from Anaconda, and another one.
Some people had a similar issue with PyTorch and PIL, not sure how it finally got resolved, but a workaround could be to use python 3.6.0 (or even 3.5) instead of 3.6.1.

**Comment by ThalerF** [comment]
Hello,

I am having the same error (`undefined symbol: PySlice_Unpack`) on Linux Mint 18.1 also using Conda and Python 3.6.0. I have tried:

- `conda remove pygpu theano && conda install -c conda-forge pygpu theano`,
- `conda remove pygpu theano && conda install pygpu theano` and
- the [step-by-step install guide](http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install-system-library-as-admin).

None of these methods fixed the problem. Has anyone found a solution for it? Also, is there a new ticket? I was not able to find one.

**Comment by nouiz** [comment]
Can you try with Python 3.5?

Le lun. 15 mai 2017 13:41, Franz Thaler, BSc <notifications@github.com> a
écrit :

**Comment by ThalerF** [comment]
I have tested Python 3.5.3 and it works on my setup, thank you.

**Comment by abergeron** [comment]
Just to note here that to actually install the conda forge version your need `conda install -c conda-forge libgpuarray theano`.  There is no `pygpu` package on conda-forge.

**Comment by Atlas7** [comment]
Had the same issue this afternoon. I implemented the suggestion of downgrading from Python 3.6 to Python 3.5 - error goes away (like magic...)

**Comment by mappagnosis** [comment]
I'm having the same issue but on Python 3.5 and installed using conda.  I have tried: 

- removing and re-installing 
- pygyp version 0.6.2, 0.6.4 and 0.6.8
- theano 0.8.2 and 0.9.0
- installing from conda-forge 
- updating python from 3.5.2 to 3.5.3 (and then reinstalling theano and pygyp)

**Comment by abergeron** [comment]
Please make a new ticket rather than commenting on an old closed one.

What happens when you try `python -c 'import pygpu'`?

**Comment by loretoparisi** [comment]
@abergeron in my case I'm running `python3` and I get

```
root@2ec43fec4281:~# python3 gpu_test.py 
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)
NoneType
root@2ec43fec4281:~# python3 -c 'import pygpu; print(pygpu.__version__)'
0.7.2+23.gace45c6
```

**Comment by abergeron** [comment]
Your Theano is not matched with your pygpu.  Theano 0.9 requires pygpu 0.6.X.  For pygpu 0.7 use 0.10bete2 or more recent.
