### ISSUE TITLE
Unable to build on Windows 7 VS2015

### ISSUE THREAD

**Issue by andyz001** [Theano/libgpuarray#422]
It has been hours, I cannot get libgpuarray build. Your help is much appreciated.
Here is the environment:
Windows 7 64bit; Visual Studio 2015; CMake 3.8; Windows SDK 10.0.15063.0;

Steps:
1. create environment variable LIB to include SDK x64 libraries
2. update environment variable PATH to include CMake, VS2015
3. run vcvarsall.bat amd64 to set 64bit target
4. run make.bat from the package, then got error below.
later I tried cmake-gui, no luck, same error.

**CMakeError.txt:**
Determining if the C compiler works failed with the following output:
Change Dir: E:/Install/Python/libgpuarray/bld/CMakeFiles/CMakeTmp

Run Build Command:"nmake" "/NOLOGO" "cmTC_b2671\fast"
	"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe" -f CMakeFiles\cmTC_b2671.dir\build.make /nologo -L                  CMakeFiles\cmTC_b2671.dir\build

	Building C object CMakeFiles/cmTC_b2671.dir/testCCompiler.c.obj

	C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe @C:\Users\..\AppData\Local\Temp\nmB4F8.tmp

testCCompiler.c

Linking C executable cmTC_b2671.exe

	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_b2671.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\link.exe /nologo @CMakeFiles\cmTC_b2671.dir\objects1.rsp @C:\Users\..\AppData\Local\Temp\nmB69E.tmp

RC Pass 1 failed to run.
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'

Stop.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'

Stop.

**Comment by lamblin** [comment]
The part about `C:\Users\..\AppData\` looks suspicious to me. Was it automatically generated? I would expect your username instead of `..`.

**Comment by andyz001** [comment]
That's right. My computer is behind corporate fire wall, for censoring purpose, I replaced username with "..".

**Comment by lamblin** [comment]
OK. I'm really not a Windows expert, sorry.
Did you use the `-G "NMake Makefiles"` option as mentioned in http://deeplearning.net/software/libgpuarray_versions/dev/installation.html#windows-specific-instructions ?

**Comment by abergeron** [comment]
Something is busted with your compile environment since cmake isn't able to compile and link its simple test program.  Fix that and the compilation should work.

**Comment by langheran** [comment]
How?

**Comment by abergeron** [comment]
We only support conda packages on windows so I can't help with specifics.
