### ISSUE TITLE
pygpu.test() fail

### ISSUE THREAD

**Issue by ysagon** [Theano/libgpuarray#450]
Hello,

I have installed pygpu 0.6.5 on python 3.6.1.

when I try to run pygpu.test(), I get a lot of errors.

Here is the complete output https://gist.github.com/ysagon/dac5643102719fe1640b62f36264f2e5

Any clue?

**Comment by abergeron** [comment]
Can you try the current master?

**Comment by ysagon** [comment]
I just noticed I was using libgpuarray 0.6.0 and pygpu 0.6.5.

I have reinstalled libgpuarray 0.6.5 and now all the tests passes.

Thanks for your help
