### ISSUE TITLE
what's the relation between pygpu.gpuarray.GpuArray and theano.gpuarray.type.GpuArrayVariable

### ISSUE THREAD

**Issue by feiga** [Theano/libgpuarray#454]
I want to use the ```pygpu.collectives.GpuComm.all_reduce()``` interface to implement data-parallel training with Theano. The ```all_reduce()``` interface expects a ```GpuArray``` argument. So I'm wondering is this ```GpuArray``` the same type with the GpuArray in Theano? What should I do if I want to pass the gpu data in ```Theano.SharedVariable``` to this API?

Thanks

**Comment by nouiz** [comment]
The pygpu GpuArray is the real array. The one in Theano is the
corresponding Symbolic array. The function inside pygpu need the real array.

To get the real data from a shared variable do:

my_shared_variable.get_value(borrow=True, return_internal_type=True)

This will return the real data. So make sure to don't change it unless you
want to change the values from the shared variables.

**Comment by feiga** [comment]
@nouiz Thanks a lot! 

I tried with 
```
my_gpu_comm.all_reduce(my_shared_variable.get_value(borrow=True,  return_internal_type=True), 'sum')
```

But it raised error that "ValueError: source and comm context differ"

Any suggestion?

**Comment by feiga** [comment]
Solved, Thanks!
