### ISSUE TITLE
MSVC 2008 build error with 0.6.7

### ISSUE THREAD

**Issue by jakirkham** [Theano/libgpuarray#461]
Am running into issues building 0.6.7 with Visual Studio 2008. Only seem to be able to build ok on the most recent copy of MSVC 2015. For more details, please see this [failed build]( https://ci.appveyor.com/project/conda-forge/libgpuarray-feedstock/build/1.0.9/job/fcetfa7a6ux8bfe3#L388 ).

Looks like this [addition]( https://github.com/Theano/libgpuarray/pull/447/files#diff-53b56c78c0960e451bcefee7a36f23aeR107 ) is causing the issue. Also this [SO question]( https://stackoverflow.com/q/32851292 ) and its [answer]( https://stackoverflow.com/a/32959521 ) seem pertinent.

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/Theano/libgpuarray/pull/460 ) is an attempt to solve this issue.

**Comment by nouiz** [comment]
Did you try with the dev version of libgpuarray or a release? Which commit
or road number for you try?

**Comment by jakirkham** [comment]
Only tried the [`v0.6.7`]( https://github.com/Theano/libgpuarray/tree/v0.6.7 ) tag. So I guess commit ( https://github.com/Theano/libgpuarray/commit/e15d70be34d07fb1c28b031b752dffe87c3360ba ).

**Comment by abergeron** [comment]
Closed by #460.  Also, #465 should ensure that we keep the source buildable on windows to avoid problems in the future.

**Comment by jakirkham** [comment]
Thanks @abergeron.

Should I try patching to get a release on conda-forge or is there a patch release with this change that I should wait for?

**Comment by abergeron** [comment]
I should get 0.6.8 out soonish, so you can wait if you want.
