### ISSUE TITLE
 segfault  error 4 in libgpuarray.so.2.1 ?

### ISSUE THREAD

**Issue by gfgkmn** [Theano/libgpuarray#473]
When i load a trained net to predict,  there is a "segmentation fault (core dumped)" 

and i use dmesg to show: 
" segfault at 0 ip 00007f03c2ebc863 sp 00007ffc315f6f78 error 4 in libgpuarray.so.2.1[7f03c2eb4000+53000]"

I use ubuntu 16.04, keras==1.0.7, theano=0.9.0.
my .theanorc is:

[global]
floatX = float32
device = cuda

[nvcc]
fastmath = True

[cuda]
root = /usr/local/cuda

if i set device=gpu, then everything is OK, but the program is too slow. I remember use gpuarray at another machine I have very quickly performance, so i want to try it. and this error happend.

I have tried master branch and tag 0.6.6, and this error still happen.

**Comment by abergeron** [comment]
Can you try with 0.6.8?

Also, do you have a script that can reproduce the problem?
