### ISSUE TITLE
invalid literal for int() with base 10: '*'

### ISSUE THREAD

**Issue by FiReTiTi** [Theano/libgpuarray#474]
Hi,

I tried to run a deep learning model using Keras with Theano backend, but I got this error and I didn't find anything online, so I don't know how to fix it:

`Using Theano backend.`
`ERROR (theano.gpuarray): Could not initialize pygpu, support disabled`
`Traceback (most recent call last):`
`  File "/home/users/thibaulg/.local/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 179, in <module>`
`    use(config.device)`
`  File "/home/users/thibaulg/.local/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 166, in use`
`    init_dev(device, preallocate=preallocate)`
`  File "/home/users/thibaulg/.local/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 65, in init_dev`
`    sched=config.gpuarray.sched)`
`  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init (pygpu/gpuarray.c:9428)`
`  File "pygpu/gpuarray.pyx", line 572, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:8858)`
`ValueError: invalid literal for int() with base 10: '*'`

Any help?

Regards,

**Comment by abergeron** [comment]
Did you try to run with `cuda*` as the device?  If so that is not supported.  Either use `cuda` to let the backend choose a GPU or use `cuda0`, `cuda1`, ...

**Comment by FiReTiTi** [comment]
Thanks, that's it.
Now I've an error because to cudnn that I've to fix :-)

**Comment by zhangzhizz** [comment]
@FiReTiTi hi,i met the problem,it is the same as you,could you tell me how to deal with it?

**Comment by lamblin** [comment]
Use `cuda` or `cuda0`, `cuda1`, `cuda2`, etc., *not* literally `cuda*`.

**Comment by FiReTiTi** [comment]
See the first answer.

I've faced many successive errors with Then since they switched to libgpuarray. So I fed up and switched to TensorFlow backend, and it much better since.

**Comment by zhangzhizz** [comment]
@FiReTiTi hi,thank you so much,i have solve this problem,but i meet a new problem.......python.exe stop work?
do you know how to deal with?

**Comment by zhangzhizz** [comment]
@FiReTiTi, @lamblin  hi,thank you so much,i have solve this problem,but i meet a new problem.......python.exe stop work?
do you know how to deal with?
