### ISSUE TITLE
Please add an "uninstall" target to cmake

### ISSUE THREAD

**Issue by madanh** [Theano/libgpuarray#477]
This would greatly help debugging installations from different sources (e.g. built from git vs conda). Thanks in advance.

**Comment by abergeron** [comment]
Apparently that is possible through something like this: https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F

Do you want to do it?

**Comment by deepali-c** [comment]
Can I offer to add this?

**Comment by abergeron** [comment]
Sure

**Comment by abergeron** [comment]
Done in #479

**Comment by madanh** [comment]
@deepali-c Thanks!
