### ISSUE TITLE
Provide a clean command to setup.py

### ISSUE THREAD

**Issue by ghisvail** [Theano/libgpuarray#478]
Please consider providing an appropriate `clean` command to your `setup.py`. There are quite a few files which are generated by the build system (`version.py` + cythonized files) and are not appropriately cleaned after running `python setup.py clean`.

**Comment by ghisvail** [comment]
Also, running `python setup.py clean` should not trigger a cythonization, as it is the case now. Instead, you should encapsulate the call to cython within a custom `build_ext` command.

**Comment by nouiz** [comment]
would be interresting to add for 0.6.10 release, but I'm not sure we will have the time to do it ourself. If someone have the time to do it, that would make sure it get it.

**Comment by deepali-c** [comment]
Please advise if we can use `git clean -dfX` to implement this?

**Comment by ghisvail** [comment]
No, `python setup.py clean` should handle it.

`git clean` only works for git repositories. It won't work for source files extracted from the release tarball on PyPI, which is the canonical source used by Linux distributions for generating packages.

**Comment by nouiz** [comment]
We don't have time for that in the short term. A PR would be welcome to get this done faster.

**Comment by abergeron** [comment]
Done in #529
