### ISSUE TITLE
clBuildError on vgg16 model

### ISSUE THREAD

**Issue by thegrandpoobah** [Theano/libgpuarray#498]
Forgive me if this the wrong project to report this bug on, but as I understand it, this is the library that is actually transpiling to OpenCL.  I tried to use Theano on an Intel i7-5557U processor (early 2015 MBP, according to Apple supporting OpenCL 1.2: https://support.apple.com/en-us/HT202823) using the OpenCL backend running under macOS (High Sierra, fully patched) and received the following error:

The model that I was using was the stock vgg16 model from the fast.ai course (https://github.com/fastai/courses/blob/master/deeplearning1/nbs/vgg16.py)

So *my* source code was:

```
from vgg16 import Vgg16

vgg = Vgg16()
vgg.compile()
model = vgg.model

batch_size = 4

val_batches = get_batches(path + 'valid', shuffle = False, batch_size = batch_size)

val_features = model.predict_generator(val_batches, batch_size * 3)
print val_features.shape
```

And the error when I run this program is:

```
<program source>:98:16: error: initializing 'float *' with an expression of type '__global float *' changes address space of pointer
    DTYPE_i0 * data_col_ptr = data_col;
               ^              ~~~~~~~~
<program source>:100:22: error: initializing 'const float *' with an expression of type 'const __global float *' changes address space of pointer
    const DTYPE_i0 * data_im_ptr = data_im + data_im_offset;
                     ^             ~~~~~~~~~~~~~~~~~~~~~~~~
```

When using the pure CPU backend, this program works fine (albeit it doesn't do anything useful).

Any thoughts? Hoping somebody finds some utility in this bug report.

**Comment by abergeron** [comment]
The kernel code that Theano generate is not always compliant with the cluda abstraction layer that allows running on both type of GPUs.  If you are interested in fixing the kernels so that they will work properly, we will happily accept PRs.

Also, I notice that you are on macOS.  Be advised that we no longer support that OpenCL runtime since it is broken in many regards.  However if it works for you then it's good.

**Comment by nouiz** [comment]
Closing as on Mac and this is on Theano. There was update on Theano that could fix that. Can you update to the dev version? If that don't fix it, open an issue on Theano, but we don't have time to support well OpenCL.
