### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by zhipengChen** [Theano/libgpuarray#500]
runtimeError: error doing operation:CUDNN_STATUS_EXECUTION_FAILED

![image](https://user-images.githubusercontent.com/13817269/29397125-c431c62e-834e-11e7-91b8-b90cf30d6ec8.png)

**Comment by zhipengChen** [comment]
![image](https://user-images.githubusercontent.com/13817269/29397790-48d5b94a-8353-11e7-9b15-25bf5027e309.png)

**Comment by nouiz** [comment]
closing as this should be in Theano and not libgpuarray. Make sure to use the latest release of libguarray and pygpu, the dev version of Theano and cudnn v7. There where fixes/workaround in Theano and cudnn v7 with such error.

If that don't fix your problem, open an issue in Theano.
