### ISSUE TITLE
Add MPI to jenkins

### ISSUE THREAD

**Issue by nouiz** [Theano/libgpuarray#505]
See: https://github.com/Theano/libgpuarray/pull/499

An error wasn't detected, we should make sure collective tests get executed. Install MPI and nccl. Note, there is a PR that bump the min nccl version to 2.0. So maybe we should do it after this PR get merged?

**Comment by slefrancois** [comment]
The jenkins dockers for PRs and buildbots now have MPI and NCCL installed and libgpuarray collectives tests run.
