### ISSUE TITLE
Another: ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)

### ISSUE THREAD

**Issue by bobyl573** [Theano/libgpuarray#513]
Searched all over for a solution to this and there doesn't seem to be one, or at least not a clear solution.

Trying to run Keras in python virtual env (tried 2.7 and 3.5) on ubuntu 16.04. but keeping getting this error message:

Using Theano backend.
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)
NoneType

Tried with Miniconda2, Anaconda package, installing Theano with conda and self-install, using conda-forge, and various combination of all that. Can someone provide a clear solution or help me understand the issue here?

oh, running Cuda 8 on nvidia gtx 1050. Also, pygpu 0.6.9 and libgpuarray both clearly installed with conda.

**Comment by ankanch** [comment]
Hi, I'm having the same issue. 
I'm running [this code](https://gist.github.com/ankanch/9dd835047c562c3867ad1a8a4296d305) on Windows 10 Pro with Python 3.5.4 installed. I have theano installed via pip.

This problem really annoying.

**Comment by nouiz** [comment]
Did you install the dev version of Theano? If not, then what is the output
of this in Python?

import pygpu.version
print pygpu.version.fullversion

**Comment by bobyl573** [comment]
I can't import pygpu in Python, throws error that no module was found

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pygpu'`

Looking at the other thread, looks like there's a problem with master version, will try checking out your suggested previous commit [https://github.com/Theano/libgpuarray/issues/514](url)

Thanks

**Comment by bobyl573** [comment]
Was able to fix the issue. For me, the solution was to create a fresh Anaconda env with all the packages installed at one time. Previously, I was using a python virtual env. With all the various versions, something must've messed up in the various package installation. Will stick to Anaconda moving forward.
