### ISSUE TITLE
 pygpu was configured but could not be imported or is too old

### ISSUE THREAD

**Issue by ankanch** [Theano/libgpuarray#514]
Hi , I'm install theano on Windows 10 Pro with Python 3.5.4 64bit.
I install theano via pip.
And I installed libgpuarray by built it myself. I also got MS VC Build Tools 2015 installed.

I tried following code in tutorials : [https://gist.github.com/ankanch/9dd835047c562c3867ad1a8a4296d305](https://gist.github.com/ankanch/9dd835047c562c3867ad1a8a4296d305)
Later I got following error:
`ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)`

How can I solve this problem?

**Comment by ankanch** [comment]
I have solved this problem , idea from https://groups.google.com/d/msg/theano-users/2oTUuKtKylE/MD8uhH3JAwAJ
By changing the content of the `.theanorc`
My script can running on GPU now.
Thanks my god.

**Comment by nouiz** [comment]
Your pygpu is probably too recent for your Theano. Downgrade it to version
0.6.9 or wait that we make the master of Theano compatible with the master
of libgpuarray. This will probably be done today.

**Comment by ankanch** [comment]
my script can running on GPU now, but the other problem is when I run `import pygpu.version`, I got this: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pygpu'
```

**Comment by nouiz** [comment]
There is problem with the master of Theano and libgpuarray around version.
We are looking into that.

So for now, use libgpuarray 0.6.9 and this Theano commit before the
problem: 8b9dc5f1c58d9da6

**Comment by thompsonisaacb** [comment]
To fix it I followed above but it was hard to read so I will summarize it here:
find  
".theanorc" file 

add the path to the gpu: 

```
[cuda] 
root = /usr/local/cuda-8.0
```

**Comment by Dateios** [comment]
conda install -c conda-forge pygpu

can solve it.
