### ISSUE TITLE
versioneer should fail when it can't find a good version

### ISSUE THREAD

**Issue by nouiz** [Theano/libgpuarray#517]
Reported by @slefrancois 

When doing a git clone depth 1, it don't clone the tag, so the version end up as "0+undefined". This make Theano fail. But I think pygpu/libgpuarray build should error out when it can't get this version.

Also, we should still handle that case I think. Not sure how.

**Comment by slefrancois** [comment]
Exact error:
`ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
 File "theano/gpuarray/__init__.py", line 204, in <module>
   use(config.device)
 File "theano/gpuarray/__init__.py", line 191, in use
   init_dev(device, preallocate=preallocate)
 File "theano/gpuarray/__init__.py", line 60, in init_dev
   pygpu_version = pygpu_parse_version(pygpu.__version__)
 File "theano/gpuarray/__init__.py", line 49, in pygpu_parse_version
   major = int(pieces[0])
ValueError: invalid literal for int() with base 10: '0+untagged'`

**Comment by abergeron** [comment]
This was done in #539
