### ISSUE TITLE
Allow installation via PIP

### ISSUE THREAD

**Issue by dwt** [Theano/libgpuarray#537]
I've noticed that it doesn't seem to be possible to install libgpuarray or pygpu via pip - is there any principled restriction or have you just not yet got around to submitting a package there?

**Comment by nouiz** [comment]
It would be hard to do. pip don't support well "real" C library libgpuarray.

Now that we build automatically conda packages with CI, maybe we could do it.

I strongly recommand that you use conda, especially on Windows. On Linux, it should be easy to install manually libgpuarray if you can't use conda.

**Comment by dwt** [comment]
@nouiz It seems you should be able to provide pre-built binaries as wheels on pypy just as you provide condo packages.

Other than that: Is there a specific reason you don't build the libgpuarray as an Extension? Seems that should be doable.

**Comment by abergeron** [comment]
We can't do that because it would need to install libgpuarray a pure C shared library, which pip cannot handle.  conda is made to handle non-python packages and therefore can work.

**Comment by abergeron** [comment]
Also, we can't just embed it in the extension since we have 4 extension modules binding to libgpuarray for different parts.
