### ISSUE TITLE
Change default device to cuda0 or cudaN

### ISSUE THREAD

**Issue by nouiz** [Theano/libgpuarray#54]
The opencl back-end is lagging and will continue for some times. So I think we should change the detault.

We also don't have an option to let the driver select the GPU like in Theano. So I think we should change that cuda mean like in Theano, let the driver decide and create cudaX that mean, reuse the existing contexte.

Another option that I don't know if it is possible is to have cuda try to reuse the existing context and if none exist, let the driver pick one? If this is possible, I think it would be better.

**Comment by abergeron** [comment]
We now have an option to let the driver select a gpu (at least for the cuda backend).

I disagree about changing the default since:
a) It is only for the tests.
b) You should specify an explicit target if you want one.
c) OpenCL support is more widely available that cuda support.

**Comment by nouiz** [comment]
I reopen as I don't agree. We have first class support for CUDA, but not for OpenCL. So we should not default to OpenCL. I don't see this changing in the futur.

**Comment by nouiz** [comment]
Just a pop of this. It happened again that this cause problem.

We don't have good OpenCL support. We don't have time to work on this in the short term, so this is a bad idea to default to something we badly support and don't have plan to fix shortly.

**Comment by nouiz** [comment]
Just to be clear, I think this should be changed in the "make test", and in pygpu. It should never default to OpenCL.

**Comment by abergeron** [comment]
The current default is no device.  The tests do print a message to that effect, but ctest hides the output unless we set some environment variable or pass a flag.

I tried to figure out a way to make ctest show error output by default from cmake, but apparently that is impossible since all the test stuff is hardcoded.  I would welcome a suggestion about a test runner that is not as retarded and convoluted as ctest.

**Comment by nouiz** [comment]
does it also block output to stderr? If not, we could write there.

Otherwise, we need to document that in the installation instruction and
when we write example of the command to run, always set the env var. So
always write:

DEVICE=cuda0 make test

instead of just make test

**Comment by abergeron** [comment]
It is already writing to stderr and it is blocked.

I'm ok with adjusting the documentation.
