### ISSUE TITLE
Pygpu installs a bizarre version

### ISSUE THREAD

**Issue by Sentient07** [Theano/libgpuarray#542]
Hi,
I just updated my pygpu to the recent version by pulling from the master. I get this error upon doing so, when importing theano

```
(macvnev) Ramanas-MacBook-Pro:Theano Ramana$ THEANO_FLAGS=device=cuda0 python -c "import theano"
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "theano/gpuarray/__init__.py", line 220, in <module>
    use(config.device)
  File "theano/gpuarray/__init__.py", line 207, in use
    init_dev(device, preallocate=preallocate)
  File "theano/gpuarray/__init__.py", line 63, in init_dev
    pygpu_version = pygpu_parse_version(pygpu.__version__)
  File "theano/gpuarray/__init__.py", line 48, in pygpu_parse_version
    assert len(pieces) == 3
AssertionError
```

and when i checked the version of pygpu, it seemed to be very unusual value,

```
(macvnev) Ramanas-MacBook-Pro:Theano Ramana$ THEANO_FLAGS=device=cuda0 python -c "import pygpu;print pygpu.__version__"
-9998+914.g2438e7a
```

Would be glad to have some help on this.

Cheers, 
Ramana

**Comment by nouiz** [comment]
the version -9998 is a very vert old version of libgpuarray.

Can you make a fresh clone of libgpuarray, delete all old installation of
it and resinstall it?

There seem to be a fix of version somewhere in your stack.

**Comment by Sentient07** [comment]
Looks like I have two clones on my system and I had installed from the wrong one. Fixed it with uninstallation and fresh clone.
