### ISSUE TITLE
pygpu was configured but could not be imported or is too old 

### ISSUE THREAD

**Issue by massimilianocomin** [Theano/libgpuarray#547]
Hi,

I installed theano, pygpu and libgpuarray on a cluster locally, through conda with the command `conda install -c mila-udem/label/pre theano pygpu libgpuarray`.
The versions I get from `conda list` are :

`libgpuarray               0.7.2.dev1           h3972f8e_0    mila-udem/label/pre`
`pygpu                     0.7.2.dev1       py35hcab9789_0    mila-udem/label/pre`
`theano                    0.10.0beta3      py35he84db1d_0    mila-udem/label/pre`

When I do `import theano` I get : 
`
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None
`

And if I do `import pygpu` I have :
`
ImportError: /lib64/libc.so.6: version 'GLIBC_2.14' not found
`

I'm using python 3.5.3.

**Comment by nouiz** [comment]
Did you found a fix? Someone else had this problem.

**Comment by massimilianocomin** [comment]
I just reposted it in Theano/Theano and closed this issue to avoid duplicate !
