### ISSUE TITLE
undefined symbol: gpucontext_props_new when building 0.7.3

### ISSUE THREAD

**Issue by bfredl** [Theano/libgpuarray#549]
I get this error when building 0.7.3 and then running. Building an earlier master (roughly 0.6) worked fine.

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-b22a183e5879> in <module>()
----> 1 import pygpu

/home/bjorn/.local/lib/python3.6/site-packages/pygpu-0.7.3+18.g65f34a1-py3.6-linux-x86_64.egg/pygpu/__init__.py in <module>()
      5     return p
      6 
----> 7 from . import gpuarray, elemwise, reduction
      8 from .gpuarray import (init, set_default_context, get_default_context,
      9                        array, zeros, empty, asarray, ascontiguousarray,

ImportError: /home/bjorn/.local/lib/python3.6/site-packages/pygpu-0.7.3+18.g65f34a1-py3.6-linux-x86_64.egg/pygpu/gpuarray.cpython-36m-x86_64-linux-gnu.so: undefined symbol: gpucontext_props_new
```

And yes, I made sure to purge the system of older libgpuarray and pygpu versions (yes I checked _both_ locations python can store user packages).

**Comment by nouiz** [comment]
I'm pretty sure there is still some left over from older libgpuarray that cause problem.

To get rid of the old installation you need to get rid of:
- The python packages pygpu
- The C library libgpuarray. This request getting rid of shared library (libgpuarray.so*) and headers 

On my installation, this mean those file:

```
$ ls ~/.local/lib/libgpuarray*
/u/bastienf/.local/lib/libgpuarray.so  /u/bastienf/.local/lib/libgpuarray.so.3  /u/bastienf/.local/lib/libgpuarray.so.3.0  /u/bastienf/.local/lib/libgpuarray-static.a
```

and that directory:

    ~/.local/include/gpuarray/

**Comment by bfredl** [comment]
Yes, I found some more. Strange,`$HOME/.local/lib/libgpuarray.so`was a symlink to  `$HOME/.local/lib/libgpuarray.so.3`, which worked,  but `setup.py` still linked the older version `$HOME/.local/lib/libgpuarray.so.2`. Removing that file, _without_ recompliling libgpuarray again fixed it. Why does it not link to the canonical/highest installed version, it if finds it to be compatible anyway?

**Comment by nouiz** [comment]
For some reason I don't know, it will first try to reuse the same version as during compilation. So it could reuse older version. If it don't find it, then it will try to find another compatible one. So it don't use the most recent version by default.

@abergeron do you think it is possible during the installation to force the remove of old version or raise an error before install if an old version is installed that won't be overrided? This would help prevent this type of problems user have (and that I also have)

**Comment by abergeron** [comment]
That is a really bad idea.  It will screw with package builds and other things of the sort.  Not to mention that you often need root to remove the older libraries.

Also, no other C package in the world does this.

**Comment by nouiz** [comment]
ok, so closing.

**Comment by bfredl** [comment]
My point has nothing to do with "removing old versions", rather if Y needs X.so.3 it should use X.so.3 even if X.so.2 is available, that's the very purpose of versioning `.so` files...

**Comment by nouiz** [comment]
This isn't in our control...

**Comment by bfredl** [comment]
You mean `distutils` is hardcoded to go out of its way to use the oldest `.so` version, instead of the newest _and_ canonical one (as I said, it _did_ update the symlink, so the system linker should use the new one), and nothing in the world can change it?

**Comment by nouiz** [comment]
@abergeron can explain it better then me. My personal resume, it don't work
to have multiple version. I always just keep one. I think Theano shared
library point to the full version number of libgpuarray during compilation.

**Comment by abergeron** [comment]
Your problem is not at compile-time (where disutils could be the culprit), but at runtime.  This means it's ls.so's fault.

Unfortunately the linux runtime linker is severely brain-damaged in some respects and needs a lot of hand-holding.  One of the things that can confuse it is that when you install new libraries, you need to run `sudo ldconfig` otherwise it will never see them.
