### ISSUE TITLE
gcc 5.1.1 : max_align_t also defined in stddef.h

### ISSUE THREAD

**Issue by mdda** [Theano/libgpuarray#55]
There's a conflicting redefinition going on for ``max_align_t`` between : 

* ``/home/andrewsm/env/libgpuarray/src/util/halloc.c`` ; and
* ``/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/stddef.h``

It looks like it could be resolved by having ``#ifndef _GCC_MAX_ALIGN_T" around the definitions in our ``halloc.c``.

Does this make sense?

**Comment by nouiz** [comment]
That seem good. Do you want to make a PR?

By the way, which OS do you use?

thanks

**Comment by mdda** [comment]
I'm on Fedora (which tends to be kind of bleeding edge - on FC22 now).

I'll do a PR this weekend, since I'm on a bit of a PyCon-talk prep deadline - and now find that Nvidia doesn't like the gcc version either : So the whole "run some GPU demo" thing is circling the drain...

I just spent a bunch of time playing with blocks inside iPython (with Bokeh) - so facing a compiler message quickly brought me back down to earth :-)
