### ISSUE TITLE
gemmBatch_3d gives incorrect results

### ISSUE THREAD

**Issue by mzoehr** [Theano/libgpuarray#554]
After several test, gemmBatch_3d failes to compute correct results in v.7.3, v.7.4 and unstable

libgpuarray-0.7.4/tests/check_blas.c:21:F:all:test_gemmBatch_3d_C:0: Difference at 0: -24.000000 != 30.000000(ref)
libgpuarray-0.7.4/tests/check_blas.c:21:F:all:test_gemmBatch_3d_F:0: Difference at 0: -4.000000 != 42.000000(ref)
libgpuarray-0.7.4/tests/check_blas.c:21:F:all:test_gemmBatch_3d_S:0: Difference at 0: -21.000000 != 14.000000(ref

Is there any fix for this?
thx. in advance

**Comment by nouiz** [comment]
Which GPU do you use? Which version of cuda and driver?

**Comment by nouiz** [comment]
as no news, closing.
