### ISSUE TITLE
by default it installs version 0.6.5. How do I install version 0.7.0?

### ISSUE THREAD

**Issue by khetan2** [Theano/libgpuarray#559]

**Comment by nouiz** [comment]
How do you install it?

Try this

conda install -c mila-udem pygpu

**Comment by iaroslav-ai** [comment]
Hey, 
I suspect you might follow the instructions here:
[http://deeplearning.net/software/theano/install_ubuntu.html](http://deeplearning.net/software/theano/install_ubuntu.html)
There in cloned repo you switch to 0.6.5 version, might be the reason why then 0.6.5 is installed

**Comment by abergeron** [comment]
I've made a PR to fix the install instructions that make you install 0.6.5 from the clone.

In the meantime, if you are installing from git, just don't use the checkout -b command.  The current master of pygpu/libgpuarray works with the current Theano.

**Comment by nouiz** [comment]
the PR to Theano is merged, so closing. thanks for the report.
