### ISSUE TITLE
extcpy cache can get overloaded

### ISSUE THREAD

**Issue by davidweichiang** [Theano/libgpuarray#75]
Hi, I've encountered a situation similar to the one addressed by PR #65, but at the level of the extcpy cache. Something in my code is causing extcpys of many different sizes, and the extcpy kernels are constantly getting regenerated. (They are cached in nvcc's ComputeCache, so the speed is still acceptable, but it does hit the disk pretty hard.) I haven't had time to dig into this sufficiently, but am submitting this issue in case you know of a quick fix similar to the power-of-two fix that worked for ReductionKernels. Thanks!

**Comment by abergeron** [comment]
I have some code to use a completely different strategy (2Q) for caching that should lessen the impact in this branch: https://github.com/abergeron/libgpuarray/tree/add_cache

This should allow the reused kernels to stay in the cache and only flush the ones that are used once. The only downside is that it requires and additional library to be built: https://github.com/abergeron/libcache

If your use case just requires a lot of often-used kernels, the other solution would be to make the cache size a configurable parameter and make it bigger.

**Comment by davidweichiang** [comment]
I figured out a little bit more -- in my code, this is being caused by concatenating 64 arrays, and `GpuArray_concatenate` calls `buffer_extcopy` with a different offset for each one.

Is there a clean way to make the size of the cache configurable? Or is there a way to avoid having each of these copies be a different kernel? Thanks...

**Comment by abergeron** [comment]
Maybe the solution would be to make the offset a parameter to the extcopy kernel and just pass it in.

Also I want to make the cache size configurable, but I also want something a little more structured for general settings.

**Comment by davidweichiang** [comment]
From my point of view, the former would certainly be preferable. But if I try to modify the PTX code, I will definitely break something :) Would this be something easy for you to do? Thanks very much!

**Comment by abergeron** [comment]
I'll take a go at it tomorrow

**Comment by abergeron** [comment]
Sorry, I didn't have the time to do it.  Maybe I'll have some time this week, but I'm not so sure.

**Comment by abergeron** [comment]
The extcpy cache overload should be avoided with the new code.  However there still isn't any mechanism to configure the cache size (or anything else).

The rest of the ticket will be addressed (eventually) by #153
