### ISSUE TITLE
Missing import for SkipTest in test_blas

### ISSUE THREAD

**Issue by jimfleming** [Theano/libgpuarray#83]
Ran into this while running tests:

https://github.com/Theano/libgpuarray/blob/master/pygpu/tests/test_blas.py#L12

- Python 2.7
- Missing Scipy installation
- Mac OS X (Yosemite)

**Comment by abergeron** [comment]
Yes, you're right.  If you want to do a fix, SkipTest should come from `from nose.plugins.skip import SkipTest`.

I might be a little too busy with other things to address it this week.

**Comment by jimfleming** [comment]
Sure thing, I can submit a PR tomorrow morning.

**Comment by abergeron** [comment]
This is fixed.
