### ISSUE TITLE
Error installing libgpuarray on Mac OSX

### ISSUE THREAD

**Issue by outlace** [Theano/libgpuarray#88]
System: MacBook Air mid 2014. Mac OSX 10.10.5

Tried to install libgpuarray from this guide: http://deeplearning.net/software/libgpuarray/installation.html

on "make" I get this error:

mycomp:Build myuser$ make
[  4%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_opencl.c.o
In file included from /Users/brandonbrown/Desktop/Projects/libgpuarray/src/gpuarray_buffer_opencl.c:4:
/Users/brandonbrown/Desktop/Projects/libgpuarray/src/private_opencl.h:7:10: fatal error: 
      'OpenCL/opencl.h' file not found
#include <OpenCL/opencl.h>
         ^
1 error generated.
make[2]: *** [src/CMakeFiles/gpuarray.dir/gpuarray_buffer_opencl.c.o] Error 1
make[1]: *** [src/CMakeFiles/gpuarray.dir/all] Error 2
make: *** [all] Error 2

Mac OSX comes with OpenCL drivers and the opencl.h header files are in the frameworks directory. Not sure why it's failing. Some linking issue?

**Comment by abergeron** [comment]
I do have a macbook air (although older) with 10.10.5 on it and the build goes well for me.

I have 
```
$ clang --version
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
installed from Xcode 7 and Command Line Tools (10.10) for Xcode

Maybe you have a different version?  I also know that the previous version of Xcode works, but if it's older than that you might have to upgrade.

Finally if you are trying to build with something else than Xcode, that isn't supported on Mac and I never test it so I wouldn't be surprised that it's broken.

**Comment by abergeron** [comment]
Since there has been no reply for a while, I'll assume that it works.  If you still have problems, please reopen.
