### ISSUE TITLE
/usr/local/lib/libgpuarray.so not found when importing pygpu on ubuntu 14.04

### ISSUE THREAD

**Issue by prinsherbert** [Theano/libgpuarray#89]
In order to use the instructions from http://deeplearning.net/software/libgpuarray/installation.html , I also needed to symlink the libgpuarray to somewhere in the default LD_LIBRARY_PATH

    sudo ln -s /usr/local/lib/libgpuarray.so /usr/lib/libgpuarray.so

Not sure why `/usr/local/lib` was not good enough, nevertheless this worked.

Before I got this message in ipython3:

    In [1]: import pygpu
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-b22a183e5879> in <module>()
    ----> 1 import pygpu
    
    /usr/local/lib/python3.4/dist-packages/pygpu-0.2.1-py3.4-linux-x86_64.egg/pygpu/__init__.py in     <module>()
          5     return p
          6 
    ----> 7 from . import gpuarray, elemwise, reduction
          8 from .gpuarray import (init, set_default_context, get_default_context,
          9                        array, zeros, empty, asarray, ascontiguousarray,
    
    ImportError: libgpuarray.so: cannot open shared object file: No such file or directory
    
    In [2]:

**Comment by abergeron** [comment]
I am on ubuntu14.04 and the system finds libgpuarray.so in /usr/local/lib correctly, so I don't know what is different with your system.

One option is to run  ldconfig to update the shared library cache, which might make the system find it.

You can also use the `-DCMAKE_INSTALL_PREFIX=/usr/lib` option to install libgpuarray there if you want.

**Comment by prinsherbert** [comment]
It's very much possible that this is a glitch on my system, nevertheless I thought it might be a good idea to create the issue, such that other googlers know a simple fix :)

**Comment by stavinsky** [comment]
I decided to not change default prefix and just add one line to `.bash_profile`. 
`export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
`
Hope this will help to someone

**Comment by alyato** [comment]
hi,I also meet this same question by the  http://deeplearning.net/software/libgpuarray/installation.html.
When i import pygpu， it show  me 
![22](https://cloud.githubusercontent.com/assets/6815071/26767979/242a1394-49d7-11e7-9d51-90379724dfd2.png)

my os is 14.04. and my .bashrc is 
![23](https://cloud.githubusercontent.com/assets/6815071/26768021/63ce807a-49d7-11e7-9d41-8eba3a21a168.png)

how can i fix this? Thanks.

**Comment by abergeron** [comment]
Please either post a message on the mailing list or create a new issue if you are sure this is a bug in pygpu/libgpuarray.  Don't post comments on closed issues.

As for your problem, where did you install libgpuarray?

**Comment by alyato** [comment]
@abergeron  Thanks. It does work now.
