### ISSUE TITLE
Can't import pygpu on Ubuntu in python after libgpuarray was installed

### ISSUE THREAD

**Issue by avostryakov** [Theano/libgpuarray#91]
I installed libgpuarray by following instructions from http://deeplearning.net/software/libgpuarray/installation.html. All looks more less ok (without clBLAS):

root@xxx:~/libgpuarray/Build# cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found CUDA: /usr/local/cuda (found version "7.0") 
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so  
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for mkstemp
-- Looking for mkstemp - found
Building with NVRTC
-- Looking for cublasSgemmEx
-- Looking for cublasSgemmEx - not found
-- Could NOT find clBLAS (missing:  CLBLAS_LIBRARIES CLBLAS_INCLUDE_DIRS) 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for one of the modules 'check'
Tests disabled because Check was not found
-- Configuring done
CMake Warning at src/CMakeLists.txt:123 (add_library):
  Cannot generate a safe runtime search path for target gpuarray because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/ubuntu/libgpuarray/Build

root@xxx:~/libgpuarray/Build# make
Scanning dependencies of target gpuarray
[  3%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_types.c.o
[  7%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_error.c.o
[ 10%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_util.c.o
[ 14%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer.c.o
[ 17%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array.c.o
[ 21%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_array_blas.c.o
[ 25%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_kernel.c.o
[ 28%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_extension.c.o
[ 32%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_strl.c.o
[ 35%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_cuda.c.o
[ 39%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_blas_cuda_cublas.c.o
[ 42%] Building C object src/CMakeFiles/gpuarray.dir/gpuarray_buffer_opencl.c.o
In file included from /usr/local/cuda/include/CL/opencl.h:44:0,
                 from /home/ubuntu/libgpuarray/src/private_opencl.h:9,
                 from /home/ubuntu/libgpuarray/src/gpuarray_buffer_opencl.c:4:
/usr/local/cuda/include/CL/cl_gl_ext.h:44:4: warning: "/*" within comment [-Wcomment]
  * /* cl_VEN_extname extension  */
 ^
[ 46%] Building C object src/CMakeFiles/gpuarray.dir/util/strb.c.o
Linking C shared library ../../lib/libgpuarray.so
[ 50%] Built target gpuarray
Scanning dependencies of target gpuarray-static
[ 53%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_types.c.o
[ 57%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_error.c.o
[ 60%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_util.c.o
[ 64%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer.c.o
[ 67%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_array.c.o
[ 71%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_array_blas.c.o
[ 75%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_kernel.c.o
[ 78%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_extension.c.o
[ 82%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_strl.c.o
[ 85%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer_cuda.c.o
[ 89%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_blas_cuda_cublas.c.o
[ 92%] Building C object src/CMakeFiles/gpuarray-static.dir/gpuarray_buffer_opencl.c.o
In file included from /usr/local/cuda/include/CL/opencl.h:44:0,
                 from /home/ubuntu/libgpuarray/src/private_opencl.h:9,
                 from /home/ubuntu/libgpuarray/src/gpuarray_buffer_opencl.c:4:
/usr/local/cuda/include/CL/cl_gl_ext.h:44:4: warning: "/*" within comment [-Wcomment]
  * /* cl_VEN_extname extension  */
 ^
[ 96%] Building C object src/CMakeFiles/gpuarray-static.dir/util/strb.c.o
Linking C static library ../../lib/libgpuarray-static.a
[100%] Built target gpuarray-static

root@xxx:~/libgpuarray/Build# make install
[ 50%] Built target gpuarray
[100%] Built target gpuarray-static
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/include/gpuarray/array.h
-- Installing: /usr/local/include/gpuarray/blas.h
-- Installing: /usr/local/include/gpuarray/buffer.h
-- Installing: /usr/local/include/gpuarray/buffer_blas.h
-- Installing: /usr/local/include/gpuarray/config.h
-- Installing: /usr/local/include/gpuarray/error.h
-- Installing: /usr/local/include/gpuarray/extension.h
-- Installing: /usr/local/include/gpuarray/ext_cuda.h
-- Installing: /usr/local/include/gpuarray/kernel.h
-- Installing: /usr/local/include/gpuarray/types.h
-- Installing: /usr/local/include/gpuarray/util.h
-- Installing: /usr/local/lib/libgpuarray.so
-- Removed runtime path from "/usr/local/lib/libgpuarray.so"
-- Installing: /usr/local/lib/libgpuarray-static.a

root@ip-10-202-167-238:~/libgpuarray/Build# cd ..
root@ip-10-202-167-238:~/libgpuarray# python setup.py build
Compiling pygpu/gpuarray.pyx because it changed.
Compiling pygpu/blas.pyx because it changed.
[1/2] Cythonizing pygpu/blas.pyx
[2/2] Cythonizing pygpu/gpuarray.pyx
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pygpu
copying pygpu/tools.py -> build/lib.linux-x86_64-2.7/pygpu
copying pygpu/__init__.py -> build/lib.linux-x86_64-2.7/pygpu
copying pygpu/elemwise.py -> build/lib.linux-x86_64-2.7/pygpu
copying pygpu/parser.py -> build/lib.linux-x86_64-2.7/pygpu
copying pygpu/reduction.py -> build/lib.linux-x86_64-2.7/pygpu
copying pygpu/_array.py -> build/lib.linux-x86_64-2.7/pygpu
copying pygpu/dtypes.py -> build/lib.linux-x86_64-2.7/pygpu
copying pygpu/operations.py -> build/lib.linux-x86_64-2.7/pygpu
creating build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/test_operations.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/test_reduction.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/test_tools.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/__init__.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/test_parser.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/main.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/support.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/test_elemwise.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/test_blas.py -> build/lib.linux-x86_64-2.7/pygpu/tests
copying pygpu/tests/test_gpu_ndarray.py -> build/lib.linux-x86_64-2.7/pygpu/tests
running build_ext
building 'pygpu.gpuarray' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pygpu
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DGPUARRAY_SHARED -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c pygpu/gpuarray.c -o build/temp.linux-x86_64-2.7/pygpu/gpuarray.o
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pygpu/gpuarray.c:265:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ufuncobject.h:317:0,
                 from pygpu/gpuarray.c:266:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pygpu/gpuarray.o -lgpuarray -o build/lib.linux-x86_64-2.7/pygpu/gpuarray.so
building 'pygpu.blas' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DGPUARRAY_SHARED -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c pygpu/blas.c -o build/temp.linux-x86_64-2.7/pygpu/blas.o
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pygpu/blas.c:265:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pygpu/blas.c:265:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ufuncobject.h:317:0,
                 from pygpu/blas.c:266:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
pygpu/blas.c:1158:25: warning: ‘__pyx_f_5pygpu_8gpuarray_typecode_to_dtype’ defined but not used [-Wunused-variable]
 static PyArray_Descr *(*__pyx_f_5pygpu_8gpuarray_typecode_to_dtype)(int); /*proto*/
                         ^
pygpu/blas.c:1159:14: warning: ‘__pyx_f_5pygpu_8gpuarray_get_typecode’ defined but not used [-Wunused-variable]
 static int (*__pyx_f_5pygpu_8gpuarray_get_typecode)(PyObject *); /*proto*/
              ^
pygpu/blas.c:1160:37: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_default_context’ defined but not used [-Wunused-variable]
 static struct PyGpuContextObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_default_context)(void); /*proto*/
                                     ^
pygpu/blas.c:1161:14: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_GpuArray_Check’ defined but not used [-Wunused-variable]
 static int (*__pyx_f_5pygpu_8gpuarray_pygpu_GpuArray_Check)(PyObject *); /*proto*/
              ^
pygpu/blas.c:1162:37: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_init’ defined but not used [-Wunused-variable]
 static struct PyGpuContextObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_init)(PyObject *); /*proto*/
                                     ^
pygpu/blas.c:1165:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_fromhostdata’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_fromhostdata)(void *, int, unsigned int, size_t const *, Py_ssize_t const *, struct PyGpuContextObject *, PyTypeObject *); /*proto*/
                                   ^
pygpu/blas.c:1166:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_fromgpudata’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_fromgpudata)(gpudata *, size_t, int, unsigned int, size_t const *, Py_ssize_t const *, struct PyGpuContextObject *, int, PyObject *, PyTypeObject *); /*proto*/
                                   ^
pygpu/blas.c:1168:14: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_move’ defined but not used [-Wunused-variable]
 static int (*__pyx_f_5pygpu_8gpuarray_pygpu_move)(struct PyGpuArrayObject *, struct PyGpuArrayObject *); /*proto*/
              ^
pygpu/blas.c:1169:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_view’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_view)(struct PyGpuArrayObject *, PyTypeObject *); /*proto*/
                                   ^
pygpu/blas.c:1170:14: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_sync’ defined but not used [-Wunused-variable]
 static int (*__pyx_f_5pygpu_8gpuarray_pygpu_sync)(struct PyGpuArrayObject *); /*proto*/
              ^
pygpu/blas.c:1171:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_empty_like’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_empty_like)(struct PyGpuArrayObject *, ga_order, int); /*proto*/
                                   ^
pygpu/blas.c:1172:25: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_as_ndarray’ defined but not used [-Wunused-variable]
 static PyArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_as_ndarray)(struct PyGpuArrayObject *); /*proto*/
                         ^
pygpu/blas.c:1173:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_index’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_index)(struct PyGpuArrayObject *, Py_ssize_t const *, Py_ssize_t const *, Py_ssize_t const *); /*proto*/
                                   ^
pygpu/blas.c:1174:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_reshape’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_reshape)(struct PyGpuArrayObject *, unsigned int, size_t const *, ga_order, int, int); /*proto*/
                                   ^
pygpu/blas.c:1175:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_transpose’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_transpose)(struct PyGpuArrayObject *, unsigned int const *); /*proto*/
                                   ^
pygpu/blas.c:1176:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_transfer’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_transfer)(struct PyGpuArrayObject *, struct PyGpuContextObject *, int); /*proto*/
                                   ^
pygpu/blas.c:1177:35: warning: ‘__pyx_f_5pygpu_8gpuarray_pygpu_concatenate’ defined but not used [-Wunused-variable]
 static struct PyGpuArrayObject *(*__pyx_f_5pygpu_8gpuarray_pygpu_concatenate)(GpuArray const **, size_t, unsigned int, int, PyTypeObject *, struct PyGpuContextObject *); /*proto*/
                                   ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pygpu/blas.o -lgpuarray -o build/lib.linux-x86_64-2.7/pygpu/blas.so
root@ip-10-202-167-238:~/libgpuarray# python setup.py install
running install
running bdist_egg
running egg_info
creating pygpu.egg-info
writing pbr to pygpu.egg-info/pbr.json
writing requirements to pygpu.egg-info/requires.txt
writing pygpu.egg-info/PKG-INFO
writing top-level names to pygpu.egg-info/top_level.txt
writing dependency_links to pygpu.egg-info/dependency_links.txt
writing manifest file 'pygpu.egg-info/SOURCES.txt'
reading manifest file 'pygpu.egg-info/SOURCES.txt'
writing manifest file 'pygpu.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/tools.py -> build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/__init__.py -> build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/elemwise.py -> build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/parser.py -> build/bdist.linux-x86_64/egg/pygpu
creating build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/test_operations.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/test_reduction.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/test_tools.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/__init__.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/test_parser.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/main.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/support.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/test_elemwise.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/test_blas.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/tests/test_gpu_ndarray.py -> build/bdist.linux-x86_64/egg/pygpu/tests
copying build/lib.linux-x86_64-2.7/pygpu/blas.so -> build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/reduction.py -> build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/_array.py -> build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/gpuarray.so -> build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/dtypes.py -> build/bdist.linux-x86_64/egg/pygpu
copying build/lib.linux-x86_64-2.7/pygpu/operations.py -> build/bdist.linux-x86_64/egg/pygpu
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tools.py to tools.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/elemwise.py to elemwise.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/parser.py to parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/test_operations.py to test_operations.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/test_reduction.py to test_reduction.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/test_tools.py to test_tools.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/test_parser.py to test_parser.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/main.py to main.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/support.py to support.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/test_elemwise.py to test_elemwise.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/test_blas.py to test_blas.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/tests/test_gpu_ndarray.py to test_gpu_ndarray.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/reduction.py to reduction.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/_array.py to _array.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/dtypes.py to dtypes.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/operations.py to operations.pyc
creating stub loader for pygpu/gpuarray.so
creating stub loader for pygpu/blas.so
byte-compiling build/bdist.linux-x86_64/egg/pygpu/gpuarray.py to gpuarray.pyc
byte-compiling build/bdist.linux-x86_64/egg/pygpu/blas.py to blas.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying pygpu/gpuarray.h -> build/bdist.linux-x86_64/egg/pygpu
copying pygpu/gpuarray_api.h -> build/bdist.linux-x86_64/egg/pygpu
copying pygpu/blas_api.h -> build/bdist.linux-x86_64/egg/pygpu
copying pygpu/numpy_compat.h -> build/bdist.linux-x86_64/egg/pygpu
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pygpu.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygpu.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygpu.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygpu.egg-info/pbr.json -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygpu.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pygpu.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
pygpu.__init__: module references __file__
pygpu.tests.main: module references __file__
creating dist
creating 'dist/pygpu-0.2.1-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pygpu-0.2.1-py2.7-linux-x86_64.egg
creating /usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg
Extracting pygpu-0.2.1-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
Adding pygpu 0.2.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pygpu-0.2.1-py2.7-linux-x86_64.egg
Processing dependencies for pygpu==0.2.1
Searching for mako>=0.7
Reading https://pypi.python.org/simple/mako/
Best match: Mako 1.0.2
Downloading https://pypi.python.org/packages/source/M/Mako/Mako-1.0.2.tar.gz#md5=d0bb0b15d94d0d455fbaf047d312cc2d
Processing Mako-1.0.2.tar.gz
Writing /tmp/easy_install-5cjuuJ/Mako-1.0.2/setup.cfg
Running Mako-1.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5cjuuJ/Mako-1.0.2/egg-dist-tmp-zqAaSm
warning: no files found matching '*.xml' under directory 'examples'
warning: no files found matching '*.mako' under directory 'examples'
warning: no files found matching 'distribute_setup.py'
warning: no files found matching 'ez_setup.py'
no previously-included directories found matching 'doc/build/output'
Adding Mako 1.0.2 to easy-install.pth file
Installing mako-render script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/Mako-1.0.2-py2.7.egg
Searching for MarkupSafe>=0.9.2
Reading https://pypi.python.org/simple/MarkupSafe/
Best match: MarkupSafe 0.23
Downloading https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz#md5=f5ab3deee4c37cd6a922fb81e730da6e
Processing MarkupSafe-0.23.tar.gz
Writing /tmp/easy_install-1ihQVy/MarkupSafe-0.23/setup.cfg
Running MarkupSafe-0.23/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1ihQVy/MarkupSafe-0.23/egg-dist-tmp-tTH9Zl
Adding MarkupSafe 0.23 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/MarkupSafe-0.23-py2.7-linux-x86_64.egg
Finished processing dependencies for pygpu==0.2.1

----------------------------------------------------------------------------------------------------------------
But in python I can't import pygpu:

root@xxx:~/libgpuarray# python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> import pygpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pygpu/__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
  File "pygpu/elemwise.py", line 5, in <module>
    from .tools import ScalarArg, ArrayArg, as_argument, check_contig, check_args, lru_cache
  File "pygpu/tools.py", line 13, in <module>
    from .dtypes import dtype_to_ctype, _fill_dtype_registry
  File "pygpu/dtypes.py", line 31, in <module>
    from . import gpuarray
ImportError: cannot import name gpuarray

**Comment by abergeron** [comment]
Either use `LD_LIBRARY_PATH=/usr/local/lib` in your environment or run `sudo ldconfig`

We should update the install instructions with this because the linux linker does not automatically search for new libraries in standard paths, apparently.

**Comment by avostryakov** [comment]
I installed a last version of the library. it's why I'm closing this issue.

**Comment by jameskyle** [comment]
I'm getting the same behavior on CentOS 7 with libgpu installed into /usr/local. 

Behavior persists if I export LD_LIBRARY_PATH and if I run sudo ldconfig.

**Comment by abergeron** [comment]
It may be that on CentOS, the default search path doesn't include /usr/local/lib.  However if you use LD_LIBRARY_PATH that should work.

Please post the exact command that is failing and all the output that you get.

**Comment by jameskyle** [comment]
I figured out what's going on with CentOS. They have some aggressive environment wiping sudo scripts that reset the roots shell environment to it's baseline when privileges are escalated.

So if you set: export LD_LIBRARY_PATH=/path/to/foo or CUDA_ROOT=/path/to/cuda then call 

    % sudo -s make

It wipes those variables and paths and sets them to default. So you have to either sudo -i and et the variables or modify the roots profile scripts to contain them by default.

**Comment by abergeron** [comment]
If you've found the problem, then all is good.
