### ISSUE TITLE
"Could NOT find clBLAS" error in CMake even when clBLAS is correctly installed

### ISSUE THREAD

**Issue by thebucc** [Theano/libgpuarray#92]
The FindclBLAS.cmake script is broken, it can't find clBLAS even if present

**Comment by thebucc** [comment]
By the way, I'm seeing the problem in Windows 7, unverified in other OSes.
I have posted a fixed version here: https://groups.google.com/forum/#!topic/clmath/nsqv-WA5SH4, how do I commit the change here, what kind of rules do you guys follow?

**Comment by abergeron** [comment]
If you have a fixed version of FindclBLAS.cmake, you can submit a PR and I'll check it out.

I'll just have to make sure it still works on linux and mac.

**Comment by thebucc** [comment]
All done. Please let me know if I haven't followed the correct procedure.

**Comment by abergeron** [comment]
Yes, the PR is good, I just have a comment to make it work on other platforms.
